// GENERATED by scripts/syncBrdbData.mjs — do not edit by hand.
// Regenerate with: just sync-brdb-data

import type { BrdbValue, BrdbVariant } from './schema';

export type BrickComponentData_AudioEmitter = {
  bEnabled: boolean;
  AudioDescriptor: number | null;
  VolumeMultiplier: number;
  PitchMultiplier: number;
  InnerRadius: number;
  MaxDistance: number;
  bSpatialization: boolean;
  FocusAzimuth: number;
  NonFocusAzimuth: number;
  NonFocusVolumeAttenuation: number;
};

export type BrickComponentData_Bearing = {
  bLimitAngle: boolean;
  LimitAngle: number;
  CurrentAngle: number;
  bAnglesArePercentages: boolean;
  bReversed: boolean;
  Damping: number;
};

export type BrickComponentData_Button = {
  PressSound: number | null;
  ReleaseSound: number | null;
  bAllowNearbyInteraction: boolean;
  bHiddenInteraction: boolean;
  PromptCustomLabel: string;
};

export type BrickComponentData_CheckPoint = {
  bRotatePlayerGravityOnSpawn: boolean;
};

export type BrickComponentData_Damage = {
  Damage: number;
  RepeatDelay: number;
  Message: string;
  ConsoleTag: string;
};

export type BrickComponentData_Interact = {
  InteractSound: number | null;
  Message: string;
  ConsoleTag: string;
  bAllowNearbyInteraction: boolean;
  bHiddenInteraction: boolean;
  PromptCustomLabel: string;
};

export type BrickComponentData_Internal_AttachedZone = {
  ZoneStartDistance: number;
  ZoneEndDistance: number;
  bIsBuildingZone: boolean;
  bIsLooseZone: boolean;
  bIsShareZone: boolean;
  bDetectPlayers: boolean;
  bDetectPlayers1: boolean;
  bDetectPlayers2: boolean;
  bDetectPlayers3: boolean;
  bDetectEntities: boolean;
  bDetectProjectiles: boolean;
  TagFilter: string;
};

export type BrickComponentData_Internal_CharacterZoneEvent = {
  bCollisionEnabled_Player: boolean;
  bCollisionEnabled_Player1: boolean;
  bCollisionEnabled_Player2: boolean;
  bCollisionEnabled_Player3: boolean;
};

export type BrickComponentData_Internal_EntityZoneEvent = {};

export type BrickComponentData_Internal_InputSplitter_V2 = {};

export type BrickComponentData_Internal_Microchip = {};

export type BrickComponentData_Internal_MicrochipInput = {
  PortLabel: string;
};

export type BrickComponentData_Internal_MicrochipOutput = {
  PortLabel: string;
};

export type BrickComponentData_Internal_ProjectileZoneEvent = {};

export type BrickComponentData_Internal_ReadBrickGrid = {};

export type BrickComponentData_Internal_ZoneEvent = {};

export type BrickComponentData_Motor = {
  bEnabled: boolean;
  Speed: number;
  Power: number;
  bLimitAngle: boolean;
  LimitAngle: number;
  CurrentAngle: number;
  bAnglesArePercentages: boolean;
  bReversed: boolean;
  Damping: number;
};

export type BrickComponentData_MotorSlider = {
  bEnabled: boolean;
  Speed: number;
  Power: number;
  bPositionsArePercentages: boolean;
  bReversed: boolean;
  Damping: number;
};

export type BrickComponentData_OneShotAudioEmitter = {
  AudioDescriptor: number | null;
  VolumeMultiplier: number;
  PitchMultiplier: number;
  InnerRadius: number;
  MaxDistance: number;
  bSpatialization: boolean;
  bEnableRepeat: boolean;
  RepeatTime: number;
  RepeatVariance: number;
  RepeatCount: number;
};

export type BrickComponentData_ProjectileSpawner = {
  ProjectileClass: number | null;
  FireSound: number | null;
  Direction: number;
  SpawnLocation: number;
  SpawnMargin: number;
  bEnabled: boolean;
  NumberOfShots: number;
  SpreadConeAngle: number;
  bSpreadBiasedTowardsCenter: boolean;
  FireRate: number;
  DamageMultiplier: number;
  SpeedMultiplier: number;
  ScaleMultiplier: number;
};

export type BrickComponentData_Rerouter = {};

export type BrickComponentData_RigidBearing = {
  TargetAngle: number;
  bAnglesArePercentages: boolean;
  bReversed: boolean;
  CurrentAngle: number;
  InterpMode: number;
  SmoothTime: number;
  TopSpeed: number;
};

export type BrickComponentData_RigidSlider = {
  TargetPosition: number;
  bPositionsArePercentages: boolean;
  bReversed: boolean;
  CurrentPosition: number;
  InterpMode: number;
  SmoothTime: number;
  TopSpeed: number;
};

export type BrickComponentData_Servo = {
  bEnabled: boolean;
  TargetAngle: number;
  Power: number;
  ActiveDamping: number;
  ForceLimit: number;
  bLimitAngle: boolean;
  LimitAngle: number;
  CurrentAngle: number;
  bAnglesArePercentages: boolean;
  bReversed: boolean;
  Damping: number;
};

export type BrickComponentData_ServoSlider = {
  bEnabled: boolean;
  TargetPosition: number;
  Power: number;
  TopSpeed: number;
  Exponent: number;
  bPositionsArePercentages: boolean;
  bReversed: boolean;
  Damping: number;
};

export type BrickComponentData_Slider = {
  bPositionsArePercentages: boolean;
  bReversed: boolean;
  Damping: number;
};

export type BrickComponentData_SpawnPoint = {
  bRotatePlayerGravityOnSpawn: boolean;
  bEnable: boolean;
};

export type BrickComponentData_Switch = {
  bEnabled: boolean;
  InteractSound: number | null;
  bAllowNearbyInteraction: boolean;
  bHiddenInteraction: boolean;
  PromptCustomLabel: string;
};

export type BrickComponentData_Target = {
  OnTime: number;
};

export type BrickComponentData_TeleportDestination = {};

export type BrickComponentData_Thruster = {
  bEnabled: boolean;
  Force: number;
  Throttle: number;
  Pitch: number;
  Yaw: number;
  bSpawnLight: boolean;
};

export type BrickComponentData_Touch = {
  BeginTouchSound: number | null;
  EndTouchSound: number | null;
  bCollisionEnabled_Player: boolean;
  bCollisionEnabled_Player1: boolean;
  bCollisionEnabled_Player2: boolean;
  bCollisionEnabled_Player3: boolean;
};

export type BrickComponentData_WireGraph_AudioReference = {
  Asset: number | null;
};

export type BrickComponentData_WireGraph_BrickAssetReference = {
  Asset: number | null;
};

export type BrickComponentData_WireGraph_DeltaTime = {};

export type BrickComponentData_WireGraph_EntityTypeReference = {
  Asset: number | null;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_Average = {
  Value: BrdbVariant;
  bIsEmpty: boolean;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_Base = {};

export type BrickComponentData_WireGraph_Exec_ArrayVar_DualRef = {};

export type BrickComponentData_WireGraph_Exec_ArrayVar_ElementOp = {
  Index: number;
  Value: BrdbVariant;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_Find = {
  Index: number;
  bFound: boolean;
  Value: BrdbVariant;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_Get = {
  bOutOfBounds: boolean;
  Index: number;
  Value: BrdbVariant;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_GetLength = {
  Length: number;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_Insert = {
  bOutOfBounds: boolean;
  Index: number;
  Value: BrdbVariant;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_MinMax = {
  Value: BrdbVariant;
  bIsEmpty: boolean;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_Pop = {
  bIsEmpty: boolean;
  Value: BrdbVariant;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_Push = {
  Value: BrdbVariant;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_RemoveAtIndex = {
  Index: number;
  bOutOfBounds: boolean;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_Resize = {
  Size: number;
  Value: BrdbVariant;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_Slice = {
  Start: number;
  Count: number;
  bOutOfBounds: boolean;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_Sort = {
  bDescending: boolean;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_Sum = {
  Value: BrdbVariant;
};

export type BrickComponentData_WireGraph_Exec_ArrayVar_Swap = {
  IndexA: number;
  IndexB: number;
  bOutOfBounds: boolean;
};

export type BrickComponentData_WireGraph_Exec_Character_AddInventoryEntity = {
  EntityType: number | null;
};

export type BrickComponentData_WireGraph_Exec_Character_AddInventoryItem = {
  Item: number | null;
};

export type BrickComponentData_WireGraph_Exec_Character_GetAim = {};

export type BrickComponentData_WireGraph_Exec_Character_GetDamage = {};

export type BrickComponentData_WireGraph_Exec_Character_GetFromController = {};

export type BrickComponentData_WireGraph_Exec_Character_IncDamage = {
  Amount: number;
};

export type BrickComponentData_WireGraph_Exec_Character_SetDamage = {
  Damage: number;
};

export type BrickComponentData_WireGraph_Exec_Character_SetInventoryEntity = {
  Slot: number;
  EntityType: number | null;
};

export type BrickComponentData_WireGraph_Exec_Character_SetInventoryItem = {
  Slot: number;
  Item: number | null;
};

export type BrickComponentData_WireGraph_Exec_Character_SetTempPermission = {
  PermissionTagStr: string;
  bPermissionEnable: boolean;
};

export type BrickComponentData_WireGraph_Exec_Character_ShowHint = {
  HintTitle: string;
  HintText: string;
};

export type BrickComponentData_WireGraph_Exec_ChatCommand = {
  CommandName: string;
  HelpText: string;
};

export type BrickComponentData_WireGraph_Exec_Controller_GetDisplayName = {};

export type BrickComponentData_WireGraph_Exec_Controller_GetFromEntity = {};

export type BrickComponentData_WireGraph_Exec_Controller_GetUserId = {};

export type BrickComponentData_WireGraph_Exec_Controller_GetUserName = {};

export type BrickComponentData_WireGraph_Exec_Controller_HasPermission = {
  PermissionName: string;
};

export type BrickComponentData_WireGraph_Exec_Controller_HasRole = {
  RoleName: string;
};

export type BrickComponentData_WireGraph_Exec_Controller_IsTrustedByBrickOwner =
  {};

export type BrickComponentData_WireGraph_Exec_Controller_SetCanRespawn = {
  bCanRespawn: boolean;
};

export type BrickComponentData_WireGraph_Exec_Controller_ShowChatMessage = {
  Message: string;
};

export type BrickComponentData_WireGraph_Exec_Controller_ShowMessageBox = {
  Title: string;
  Message: string;
};

export type BrickComponentData_WireGraph_Exec_Controller_ShowStatusMessage = {
  Message: string;
};

export type BrickComponentData_WireGraph_Exec_Cycle = {
  Count: number;
  Value: number;
};

export type BrickComponentData_WireGraph_Exec_Entity_GetTag = {
  Tag: string;
};

export type BrickComponentData_WireGraph_Exec_Entity_PlayAudioAt = {
  AudioDescriptor: number | null;
  VolumeMultiplier: number;
  PitchMultiplier: number;
  InnerRadius: number;
  MaxDistance: number;
  bSpatialization: boolean;
};

export type BrickComponentData_WireGraph_Exec_Entity_SetFrozen = {
  bFrozen: boolean;
};

export type BrickComponentData_WireGraph_Exec_Entity_SetTag = {
  Tag: string;
};

export type BrickComponentData_WireGraph_Exec_Gamemode_BroadcastChatMessage = {
  Message: string;
};

export type BrickComponentData_WireGraph_Exec_Gamemode_BroadcastStatusMessage =
  {
    Message: string;
    bFlashIfUnchanged: boolean;
  };

export type BrickComponentData_WireGraph_Exec_Gamemode_FillArrayFromTeamMembers =
  {};

export type BrickComponentData_WireGraph_Exec_Gamemode_GetCurrentRound = {};

export type BrickComponentData_WireGraph_Exec_Gamemode_GetLeaderboardValue = {
  Key: string;
};

export type BrickComponentData_WireGraph_Exec_Gamemode_GetTeam = {};

export type BrickComponentData_WireGraph_Exec_Gamemode_GetTeamByName = {
  TeamName: string;
};

export type BrickComponentData_WireGraph_Exec_Gamemode_GetTeamLeaderboardValue =
  {
    Key: string;
  };

export type BrickComponentData_WireGraph_Exec_Gamemode_GetTeamName = {};

export type BrickComponentData_WireGraph_Exec_Gamemode_LeaderboardValue = {
  Key: string;
  Value: number;
};

export type BrickComponentData_WireGraph_Exec_Gamemode_PlayerWins = {
  bTeamWinsInstead: boolean;
};

export type BrickComponentData_WireGraph_Exec_Gamemode_SetTeam = {
  bPinPlayerToTeam: boolean;
};

export type BrickComponentData_WireGraph_Exec_Gamemode_SetTeamPinned = {
  bPinned: boolean;
};

export type BrickComponentData_WireGraph_Exec_Gamemode_TeamLeaderboardValue = {
  Key: string;
  Value: number;
};

export type BrickComponentData_WireGraph_Exec_Gamemode_TeamWins = {};

export type BrickComponentData_WireGraph_Exec_PlayGlobalAudio = {
  AudioDescriptor: number | null;
  VolumeMultiplier: number;
  PitchMultiplier: number;
};

export type BrickComponentData_WireGraph_Exec_PrintToConsole = {
  Text: string;
};

export type BrickComponentData_WireGraph_Exec_Random = {
  Min: BrdbVariant;
  Max: BrdbVariant;
};

export type BrickComponentData_WireGraph_Exec_Toggle = {
  Value: boolean;
};

export type BrickComponentData_WireGraph_Exec_Var_EditOrGet = {
  Value: BrdbVariant;
};

export type BrickComponentData_WireGraph_Exec_Var_Get = {
  Value: BrdbVariant;
};

export type BrickComponentData_WireGraph_ExecBranch = {
  bCond: boolean;
};

export type BrickComponentData_WireGraph_ExecUnion = {};

export type BrickComponentData_WireGraph_Expr_Bool_Bool = {
  bInput: boolean;
};

export type BrickComponentData_WireGraph_Expr_BoolBool_Bool = {
  bInputA: boolean;
  bInputB: boolean;
};

export type BrickComponentData_WireGraph_Expr_ChangeDetector = {
  Input: BrdbVariant;
  bPulseOnChange: boolean;
};

export type BrickComponentData_WireGraph_Expr_ChangeDetectorExec = {
  Input: BrdbVariant;
};

export type BrickComponentData_WireGraph_Expr_Compare = {
  InputA: BrdbVariant;
  InputB: BrdbVariant;
};

export type BrickComponentData_WireGraph_Expr_Convert = {
  Input: BrdbVariant;
  Output: BrdbVariant;
  TargetType: BrdbVariant;
};

export type BrickComponentData_WireGraph_Expr_EdgeDetector = {
  Input: number;
  bPulseOnRisingEdge: boolean;
  bPulseOnFallingEdge: boolean;
};

export type BrickComponentData_WireGraph_Expr_EdgeDetectorExec = {
  Input: number;
};

export type BrickComponentData_WireGraph_Expr_Float_Float = {
  Input: number;
};

export type BrickComponentData_WireGraph_Expr_Int_Int = {
  Input: number;
};

export type BrickComponentData_WireGraph_Expr_IntInt_Int = {
  InputA: number;
  InputB: number;
};

export type BrickComponentData_WireGraph_Expr_MakeColor = {
  R: number;
  G: number;
  B: number;
  A: number;
};

export type BrickComponentData_WireGraph_Expr_MakeColorHex = {
  Hex: string;
};

export type BrickComponentData_WireGraph_Expr_MakeColorSRGB = {
  R: number;
  G: number;
  B: number;
  A: number;
};

export type BrickComponentData_WireGraph_Expr_MakeQuaternion = {
  X: number;
  Y: number;
  Z: number;
  W: number;
};

export type BrickComponentData_WireGraph_Expr_MakeRotation = {
  Pitch: number;
  Yaw: number;
  Roll: number;
};

export type BrickComponentData_WireGraph_Expr_MakeVector = {
  X: number;
  Y: number;
  Z: number;
};

export type BrickComponentData_WireGraph_Expr_MathAtan2 = {
  Y: number;
  X: number;
};

export type BrickComponentData_WireGraph_Expr_MathBlend = {
  Blend: number;
  bClampAlpha: boolean;
  InputA: BrdbVariant;
  InputB: BrdbVariant;
};

export type BrickComponentData_WireGraph_Expr_MathClamp = {
  Min: BrdbVariant;
  Max: BrdbVariant;
  Input: BrdbVariant;
};

export type BrickComponentData_WireGraph_Expr_MathCompare = {
  InputA: BrdbVariant;
  InputB: BrdbVariant;
};

export type BrickComponentData_WireGraph_Expr_MathEasing = {
  Blend: number;
  Function: number;
  Direction: number;
  InputA: BrdbVariant;
  InputB: BrdbVariant;
};

export type BrickComponentData_WireGraph_Expr_MathLogBase = {
  Input: number;
  Base: number;
};

export type BrickComponentData_WireGraph_Expr_MathPow = {
  Input: number;
  Exponent: number;
};

export type BrickComponentData_WireGraph_Expr_NearlyEqual = {
  InputA: BrdbVariant;
  InputB: BrdbVariant;
  Tolerance: number;
};

export type BrickComponentData_WireGraph_Expr_PrimMathVariant_PrimMathVariant =
  {
    Input: BrdbVariant;
  };

export type BrickComponentData_WireGraph_Expr_PrimMathVariantPrimMathVariant_PrimMathVariant =
  {
    InputA: BrdbVariant;
    InputB: BrdbVariant;
  };

export type BrickComponentData_WireGraph_Expr_Select = {
  bSelectB: boolean;
  InputA: BrdbVariant;
  InputB: BrdbVariant;
};

export type BrickComponentData_WireGraph_Expr_String_Concatenate = {
  InputA: string;
  InputB: string;
  Separator: string;
};

export type BrickComponentData_WireGraph_Expr_String_Contains = {
  Input: string;
  Search: string;
  bCaseSensitive: boolean;
};

export type BrickComponentData_WireGraph_Expr_String_EndsWith = {
  Input: string;
  Suffix: string;
  bCaseSensitive: boolean;
};

export type BrickComponentData_WireGraph_Expr_String_Find = {
  Input: string;
  Search: string;
  bCaseSensitive: boolean;
};

export type BrickComponentData_WireGraph_Expr_String_FormatText = {
  FormatString: string;
  InputA: BrdbVariant;
  InputB: BrdbVariant;
  InputC: BrdbVariant;
  InputD: BrdbVariant;
  InputE: BrdbVariant;
  InputF: BrdbVariant;
  InputG: BrdbVariant;
};

export type BrickComponentData_WireGraph_Expr_String_Length = {
  Input: string;
};

export type BrickComponentData_WireGraph_Expr_String_ParseInt = {
  Input: string;
};

export type BrickComponentData_WireGraph_Expr_String_ParseNumber = {
  Input: string;
};

export type BrickComponentData_WireGraph_Expr_String_Replace = {
  Input: string;
  Search: string;
  Replacement: string;
  bCaseSensitive: boolean;
};

export type BrickComponentData_WireGraph_Expr_String_Split = {
  Input: string;
  Delimiter: string;
  bCaseSensitive: boolean;
};

export type BrickComponentData_WireGraph_Expr_String_StartsWith = {
  Input: string;
  Prefix: string;
  bCaseSensitive: boolean;
};

export type BrickComponentData_WireGraph_Expr_String_Substring = {
  Input: string;
  Start: number;
  Length: number;
};

export type BrickComponentData_WireGraph_Expr_String_ToLower = {
  Input: string;
};

export type BrickComponentData_WireGraph_Expr_String_ToUpper = {
  Input: string;
};

export type BrickComponentData_WireGraph_Expr_String_Trim = {
  Input: string;
};

export type BrickComponentData_WireGraph_Expr_Swap = {
  bSwap: boolean;
  InputA: BrdbVariant;
  InputB: BrdbVariant;
};

export type BrickComponentData_WireGraph_Expr_Variant_Variant = {
  Input: BrdbVariant;
};

export type BrickComponentData_WireGraph_Fake_CharacterDamageEvent = {};

export type BrickComponentData_WireGraph_Fake_CharacterDeathEvent = {};

export type BrickComponentData_WireGraph_Fake_CharacterEvent = {};

export type BrickComponentData_WireGraph_Fake_ControllerEvent = {};

export type BrickComponentData_WireGraph_Fake_RoundEvent = {
  RoundNumber: number;
};

export type BrickComponentData_WireGraph_FindPlayer = {
  Query: string;
};

export type BrickComponentData_WireGraph_FontReference = {
  Asset: number | null;
};

export type BrickComponentData_WireGraph_ItemReference = {
  Asset: number | null;
};

export type BrickComponentData_WireGraph_OneShotAudioReference = {
  Asset: number | null;
};

export type BrickComponentData_WireGraph_ParticleReference = {
  Asset: number | null;
};

export type BrickComponentData_WireGraph_PickupReference = {
  Asset: number | null;
};

export type BrickComponentData_WireGraph_ProjectileReference = {
  Asset: number | null;
};

export type BrickComponentData_WireGraph_ServerUptime = {};

export type BrickComponentData_WireGraph_WheelEngineAudioReference = {
  Asset: number | null;
};

export type BrickComponentData_WireGraphPseudo_ArrayVar = {
  Value: BrdbVariant;
};

export type BrickComponentData_WireGraphPseudo_BufferSeconds = {
  SecondsToWait: number;
  ZeroSecondsToWait: number;
  CurrentTime: number;
  Input: BrdbVariant;
  Output: BrdbVariant;
  Buffered: BrdbVariant;
  bHasQueued: boolean;
  bIsOffTimer: boolean;
};

export type BrickComponentData_WireGraphPseudo_BufferTicks = {
  TicksToWait: number;
  ZeroTicksToWait: number;
  CurrentTicks: number;
  Input: BrdbVariant;
  Output: BrdbVariant;
  Buffered: BrdbVariant;
  bHasQueued: boolean;
  bIsOffTimer: boolean;
};

export type BrickComponentData_WireGraphPseudo_Timer = {
  Limit: number;
  Time: number;
  bRunning: boolean;
};

export type BrickComponentData_WireGraphPseudo_Tween = {
  Target: BrdbVariant;
  Value: BrdbVariant;
  StartValue: BrdbVariant;
  Duration: number;
  Elapsed: number;
  Function: number;
  Direction: number;
};

export type BrickComponentData_WireGraphPseudo_Var = {
  Value: BrdbVariant;
};

export type BrickComponentWireControl_DriveAndSteer = {};

export type BrickComponentWirePortControl_TeleportDestination = {};

export type BRInventoryEntryConfig = {
  Item: BrdbVariant;
};

export type BRInventoryEntryEntity = {
  EntityType: number | null;
};

export type BRInventoryEntryNothing = {};

export type BRQueueSecondsEntry = {
  Data: BrdbVariant[];
  RemainingTime: number;
};

export type BRQueueTicksEntry = {
  Data: BrdbVariant[];
  RemainingTicks: number;
};

export type BRSavedBrickComponentTypeCounter = {
  TypeIndex: number;
  NumInstances: number;
};

export type Color = {
  B: number;
  G: number;
  R: number;
  A: number;
};

export type IntVector = {
  X: number;
  Y: number;
  Z: number;
};

export type LinearColor = {
  R: number;
  G: number;
  B: number;
  A: number;
};

export type Quat = {
  X: number;
  Y: number;
  Z: number;
  W: number;
};

export type Quat4f = {
  X: number;
  Y: number;
  Z: number;
  W: number;
};

export type Rotator = {
  Pitch: number;
  Yaw: number;
  Roll: number;
};

export type Rotator3f = {
  Pitch: number;
  Yaw: number;
  Roll: number;
};

export type Vector = {
  X: number;
  Y: number;
  Z: number;
};

export type Vector2f = {
  X: number;
  Y: number;
};

export type Vector3f = {
  X: number;
  Y: number;
  Z: number;
};

export type Vector4 = {
  X: number;
  Y: number;
  Z: number;
  W: number;
};

export type WireGraphBoolArray = {
  Values: boolean[];
};

export type WireGraphDoubleArray = {
  Values: number[];
};

export type WireGraphEnumArray_EBRColorSpace = {
  Values: number[];
};

export type WireGraphEnumArray_EBRDisplayTextEasing = {
  Values: number[];
};

export type WireGraphEnumArray_EBRDisplayTextJustification = {
  Values: number[];
};

export type WireGraphEnumArray_EBREasingDirection = {
  Values: number[];
};

export type WireGraphEnumArray_EBREasingFunction = {
  Values: number[];
};

export type WireGraphEnumArray_EBrickAxis = {
  Values: number[];
};

export type WireGraphEnumArray_EBrickDirection = {
  Values: number[];
};

export type WireGraphEnumArray_EBrickMaterial = {
  Values: number[];
};

export type WireGraphEnumArray_EBrickRigidJointInterpMode = {
  Values: number[];
};

export type WireGraphEnumArray_EBRPawnCollisionChannel = {
  Values: number[];
};

export type WireGraphEnumArray_EBRTextFacing = {
  Values: number[];
};

export type WireGraphEnumArray_EBRTextMaterial = {
  Values: number[];
};

export type WireGraphEnumArray_EBRTextOutline = {
  Values: number[];
};

export type WireGraphEnumArray_EBRTextShading = {
  Values: number[];
};

export type WireGraphEnumArray_EBRTextTypeface = {
  Values: number[];
};

export type WireGraphEnumArray_EProjectileSpawnLocation = {
  Values: number[];
};

export type WireGraphEnumArrayWrapper = {
  Enum: BrdbVariant;
};

export type WireGraphEnumWrapper = {
  Enum: BrdbVariant;
};

export type WireGraphExec = {};

export type WireGraphInt64Array = {
  Values: number[];
};

export type WireGraphObjectArray = {
  Values: (number | null)[];
};

export type WireGraphStringArray = {
  Values: string[];
};

export type BrickComponentData_BrickPropertyChanger = {
  bVisibility: boolean;
  bCollisionEnabled: boolean;
  bCollisionEnabled_Player: boolean;
  bCollisionEnabled_Player1: boolean;
  bCollisionEnabled_Player2: boolean;
  bCollisionEnabled_Player3: boolean;
  bCollisionEnabled_Weapon: boolean;
  bCollisionEnabled_Interaction: boolean;
  bCollisionEnabled_Physics: boolean;
  Color: Color;
  MaterialAlpha: number;
  Material: number;
};

export type BrickComponentData_Gyroscope = {
  bEnabled: boolean;
  Strength: number;
  Damping: number;
  MaxForce: number;
  TargetAxis: Vector;
};

export type BrickComponentData_ItemSpawn = {
  PickupClass: number | null;
  bPickupEnabled: boolean;
  bPickupRespawnOnMinigameReset: boolean;
  PickupMinigameResetRespawnDelay: number;
  bPickupAutoDisableOnPickup: boolean;
  PickupRespawnTime: number;
  bRenderTranslucentWhenDisabled: boolean;
  DamageMultiplier: number;
  WeaponSpeedMultiplier: number;
  ItemNameOverride: string;
  ProjectileOverride: number | null;
  PickupOffsetDirection: number;
  PickupOffsetDistance: number;
  PickupRotation: Rotator3f;
  PickupScale: number;
  bOverridePickupColors: boolean;
  PickupMeshColors: Color[];
  bPickupAnimationEnabled: boolean;
  PickupAnimationAxis: number;
  bPickupAnimationAxisLocal: boolean;
  PickupSpinSpeed: number;
  PickupBobSpeed: number;
  PickupBobHeight: number;
  PickupAnimationPhase: number;
};

export type BrickComponentData_Joint_Wheel = {
  Control_DriveAndSteer: BrickComponentWireControl_DriveAndSteer;
  bEnabled: boolean;
  DriveSpeed: number;
  DrivePower: number;
  bSteerEnabled: boolean;
  Steer: number;
  SteerLimitDegree: number;
  SteerPower: number;
  bSuspensionEnabled: boolean;
  SuspensionStiffness: number;
  SuspensionDamping: number;
  JointDistance: number;
  bDriveWhenNotAttachedToEngine: boolean;
  bCanBrake: boolean;
  bAllowEngineSteerCorrect: boolean;
  bReversed: boolean;
  Damping: number;
};

export type BrickComponentData_Joint_Wheel_Suspension = {
  Control_DriveAndSteer: BrickComponentWireControl_DriveAndSteer;
  bEnabled: boolean;
  DriveSpeed: number;
  DrivePower: number;
  bSteerEnabled: boolean;
  Steer: number;
  SteerLimitDegree: number;
  SteerPower: number;
  bSuspensionEnabled: boolean;
  SuspensionStiffness: number;
  SuspensionDamping: number;
  SuspensionOffset: number;
  SuspensionLength: number;
  JointDistance: number;
  bDriveWhenNotAttachedToEngine: boolean;
  bCanBrake: boolean;
  bAllowEngineSteerCorrect: boolean;
  bReversed: boolean;
  Damping: number;
};

export type BrickComponentData_PointLight = {
  bMatchBrickShape: boolean;
  bEnabled: boolean;
  Brightness: number;
  Radius: number;
  Color: Color;
  bUseBrickColor: boolean;
  bCastShadows: boolean;
};

export type BrickComponentData_PrefabSpawn = {
  Prefab: string;
  SpawnOffset: Vector;
  SpawnOffsetRotation: Rotator;
  SpawnVelocity: Vector;
  bSpawnEnable: boolean;
  RespawnTime: number;
  SpawnedEntityIds: number[];
};

export type BrickComponentData_Seat_V2 = {
  bIsOccupied: boolean;
  ExitOffset: IntVector;
  bRollCameraInThirdPerson: boolean;
  bAllowNearbyInteraction: boolean;
  bHiddenInteraction: boolean;
  PromptCustomLabel: string;
};

export type BrickComponentData_SpotLight = {
  Rotation: Rotator3f;
  InnerConeAngle: number;
  OuterConeAngle: number;
  bEnabled: boolean;
  Brightness: number;
  Radius: number;
  Color: Color;
  bUseBrickColor: boolean;
  bCastShadows: boolean;
};

export type BrickComponentData_TextDisplay = {
  Text: string;
  Font: number | null;
  Rotation: number;
  Skew: number;
  Kerning: number;
  LineHeight: number;
  LineOffset: number;
  Anchor: Vector2f;
  Offset: Vector3f;
  Color: Color;
  MaterialSlider: number;
  ShadingWidth: number;
  OutlineColor: Color;
  OutlineWidth: number;
  ScuffWidth: number;
  GraffitiDepthLimit: number;
  GraffitiAngleLimit: number;
  GraffitiLayer: number;
  bEnabled: boolean;
  Face: number;
  bAlignToWedge: boolean;
  bOverrideColor: boolean;
  Typeface: number;
  Billboard: number;
  Material: number;
  Shading: number;
  bFlipShading: boolean;
  Outline: number;
  bSharpCorners: boolean;
  bSharpOutlines: boolean;
  bOverrideOutlineColor: boolean;
  bForeground: boolean;
};

export type BrickComponentData_WeightBrick = {
  Mass: number;
  MassSize: IntVector;
  MassOffset: IntVector;
};

export type BrickComponentData_WheelEngine_V2 = {
  bEnabled: boolean;
  bEnableManualControl: boolean;
  ManualInput_Drive: number;
  ManualInput_Steer: number;
  bManualInput_Brake: boolean;
  Control_DriveAndSteer: BrickComponentWireControl_DriveAndSteer;
  CustomMass: number;
  CustomMassVerticalOffset: number;
  DriveInterpSpeed: number;
  DriveSpeed: number;
  DriveAcceleratingPowerMultiplier: number;
  DriveBrakingPowerMultiplier: number;
  DriveDampingMultiplier: number;
  SteerPowerMultiplier: number;
  WheelFrictionMultiplier: number;
  SteerInterpSpeed: number;
  SteerLimitSpeedFalloff: number;
  SteerLimitDegree: number;
  CenterOfSteering: number;
  bTankSteering: boolean;
  TankSteerSpeedMultiplier: number;
  bAutoRight: boolean;
  WaterDriveForce: number;
  WaterSteeringForce: number;
  AudioDescriptor: number | null;
};

export type BrickComponentData_WireGraph_Exec_Character_AddInventoryBrick = {
  BrickAsset: number | null;
  ProceduralSize: Vector;
};

export type BrickComponentData_WireGraph_Exec_Character_AddInventoryEntry = {
  Entry: BRInventoryEntryConfig;
};

export type BrickComponentData_WireGraph_Exec_Character_AddInventoryItemAdv = {
  ItemType: number | null;
  DamageMultiplier: number;
  WeaponSpeedMultiplier: number;
  ItemScale: number;
  ItemNameOverride: string;
  ProjectileOverride: number | null;
  bOverrideColors: boolean;
  MeshColors: Color[];
};

export type BrickComponentData_WireGraph_Exec_Character_SetInventoryBrick = {
  Slot: number;
  BrickAsset: number | null;
  ProceduralSize: Vector;
};

export type BrickComponentData_WireGraph_Exec_Character_SetInventoryItemAdv = {
  Slot: number;
  ItemType: number | null;
  DamageMultiplier: number;
  WeaponSpeedMultiplier: number;
  ItemScale: number;
  ItemNameOverride: string;
  ProjectileOverride: number | null;
  bOverrideColors: boolean;
  MeshColors: Color[];
};

export type BrickComponentData_WireGraph_Exec_Controller_DisplayText = {
  Text: string;
  AnchorX: number;
  AnchorY: number;
  PositionX: number;
  PositionY: number;
  Angle: number;
  ScaleX: number;
  ScaleY: number;
  FontSize: number;
  FontColor: Color;
  OutlineSize: number;
  OutlineColor: Color;
  Justification: number;
  Transition: number;
  Easing: number;
  Lifetime: number;
  TextId: number;
};

export type BrickComponentData_WireGraph_Exec_Entity_AddLocationRotation = {
  Vector: Vector;
  Rotation: Rotator;
};

export type BrickComponentData_WireGraph_Exec_Entity_AddVelocity = {
  Vector: Vector;
  Rotation: Vector;
};

export type BrickComponentData_WireGraph_Exec_Entity_GetAngularVelocity = {
  AngularVelocity: Vector;
};

export type BrickComponentData_WireGraph_Exec_Entity_GetLinearVelocity = {
  LinearVelocity: Vector;
};

export type BrickComponentData_WireGraph_Exec_Entity_GetLocation = {
  Vector: Vector;
};

export type BrickComponentData_WireGraph_Exec_Entity_GetLocationRotation = {
  Vector: Vector;
  Rotation: Rotator;
};

export type BrickComponentData_WireGraph_Exec_Entity_GetRotation = {
  Rotation: Rotator;
};

export type BrickComponentData_WireGraph_Exec_Entity_GetVelocity = {
  Vector: Vector;
  Rotation: Vector;
};

export type BrickComponentData_WireGraph_Exec_Entity_RelativeTeleport = {
  Source: BrickComponentWirePortControl_TeleportDestination;
  Destination: BrickComponentWirePortControl_TeleportDestination;
};

export type BrickComponentData_WireGraph_Exec_Entity_SetAngularVelocity = {
  AngularVelocity: Vector;
};

export type BrickComponentData_WireGraph_Exec_Entity_SetGravityDirection = {
  Rotation: Rotator;
};

export type BrickComponentData_WireGraph_Exec_Entity_SetLinearVelocity = {
  LinearVelocity: Vector;
};

export type BrickComponentData_WireGraph_Exec_Entity_SetLocation = {
  Vector: Vector;
};

export type BrickComponentData_WireGraph_Exec_Entity_SetLocationRotation = {
  Vector: Vector;
  Rotation: Rotator;
};

export type BrickComponentData_WireGraph_Exec_Entity_SetRotation = {
  Rotation: Rotator;
};

export type BrickComponentData_WireGraph_Exec_Entity_SetVelocity = {
  Vector: Vector;
  Rotation: Vector;
};

export type BrickComponentData_WireGraph_Exec_Entity_Teleport = {
  Destination: BrickComponentWirePortControl_TeleportDestination;
};

export type BrickComponentData_WireGraph_Exec_PrefabSpawner = {
  Prefab: string;
  SpawnOffset: Vector;
  SpawnOffsetRotation: Rotator;
  SpawnVelocity: Vector;
  Lifetime: number;
  Limit: number;
  SpawnedEntityIds: number[];
};

export type BrickComponentData_WireGraph_Exec_Sweep = {
  Origin: Vector;
  Direction: Vector;
  Distance: number;
  Radius: number;
  bDetectBricks: boolean;
  bDetectPlayers1: boolean;
  bDetectPlayers2: boolean;
  bDetectPlayers3: boolean;
  bDetectPlayers4: boolean;
  bDetectPhysics: boolean;
  bDetectMap: boolean;
  bRelative: boolean;
  bIgnoreOwningGrid: boolean;
  HitLocation: Vector;
  HitNormal: Vector;
  HitDistance: number;
};

export type BrickComponentData_WireGraph_Expr_ColorBlend = {
  ColorA: LinearColor;
  ColorB: LinearColor;
  Alpha: number;
  BlendSpace: number;
  bClampAlpha: boolean;
};

export type BrickComponentData_WireGraph_Expr_ColorConvert = {
  Input: LinearColor;
  FromSpace: number;
  ToSpace: number;
};

export type BrickComponentData_WireGraph_Expr_ColorToHex = {
  Input: LinearColor;
};

export type BrickComponentData_WireGraph_Expr_DirectionToRotation = {
  Direction: Vector;
};

export type BrickComponentData_WireGraph_Expr_InvertRotation = {
  Input: Quat;
};

export type BrickComponentData_WireGraph_Expr_QuatAngleBetween = {
  InputA: Quat;
  InputB: Quat;
};

export type BrickComponentData_WireGraph_Expr_QuatBetween = {
  From: Vector;
  To: Vector;
};

export type BrickComponentData_WireGraph_Expr_QuatDotProduct = {
  InputA: Quat;
  InputB: Quat;
};

export type BrickComponentData_WireGraph_Expr_QuatFromAxisAngle = {
  Axis: Vector;
  Angle: number;
};

export type BrickComponentData_WireGraph_Expr_QuatSlerp = {
  InputA: Quat;
  InputB: Quat;
  Alpha: number;
  bShortestPath: boolean;
  bClampAlpha: boolean;
};

export type BrickComponentData_WireGraph_Expr_QuatToAxisAngle = {
  Input: Quat;
};

export type BrickComponentData_WireGraph_Expr_RotateVector = {
  Rotation: Quat;
  Vector: Vector;
};

export type BrickComponentData_WireGraph_Expr_RotationToDirection = {
  Rotation: Quat;
};

export type BrickComponentData_WireGraph_Expr_SplitColor = {
  Input: LinearColor;
};

export type BrickComponentData_WireGraph_Expr_SplitColorSRGB = {
  Input: LinearColor;
};

export type BrickComponentData_WireGraph_Expr_SplitQuaternion = {
  Input: Quat;
};

export type BrickComponentData_WireGraph_Expr_SplitRotation = {
  Input: Rotator;
};

export type BrickComponentData_WireGraph_Expr_SplitVector = {
  Input: Vector;
};

export type BrickComponentData_WireGraph_Expr_Vec_Float = {
  Input: Vector;
};

export type BrickComponentData_WireGraph_Expr_Vec_Vec = {
  Input: Vector;
};

export type BrickComponentData_WireGraph_Expr_VecFloat_Vec = {
  Input: Vector;
  Scalar: number;
};

export type BrickComponentData_WireGraph_Expr_VecVec_Float = {
  InputA: Vector;
  InputB: Vector;
};

export type BrickComponentData_WireGraph_Expr_VecVec_Vec = {
  InputA: Vector;
  InputB: Vector;
};

export type BrickComponentData_WireGraphPseudo_Dampen = {
  Target: BrdbVariant;
  Value: BrdbVariant;
  SmoothTime: number;
  Velocity: Vector4;
};

export type BrickComponentData_WireGraphPseudo_QueueSeconds = {
  SecondsToWait: number;
  Entries: BRQueueSecondsEntry[];
  DataIn1: BrdbVariant;
  DataIn2: BrdbVariant;
  DataIn3: BrdbVariant;
  DataIn4: BrdbVariant;
  DataIn5: BrdbVariant;
  DataIn6: BrdbVariant;
  DataIn7: BrdbVariant;
  DataIn8: BrdbVariant;
  DataOut1: BrdbVariant;
  DataOut2: BrdbVariant;
  DataOut3: BrdbVariant;
  DataOut4: BrdbVariant;
  DataOut5: BrdbVariant;
  DataOut6: BrdbVariant;
  DataOut7: BrdbVariant;
  DataOut8: BrdbVariant;
};

export type BrickComponentData_WireGraphPseudo_QueueTicks = {
  TicksToWait: number;
  Entries: BRQueueTicksEntry[];
  DataIn1: BrdbVariant;
  DataIn2: BrdbVariant;
  DataIn3: BrdbVariant;
  DataIn4: BrdbVariant;
  DataIn5: BrdbVariant;
  DataIn6: BrdbVariant;
  DataIn7: BrdbVariant;
  DataIn8: BrdbVariant;
  DataOut1: BrdbVariant;
  DataOut2: BrdbVariant;
  DataOut3: BrdbVariant;
  DataOut4: BrdbVariant;
  DataOut5: BrdbVariant;
  DataOut6: BrdbVariant;
  DataOut7: BrdbVariant;
  DataOut8: BrdbVariant;
};

export type BrickTypeNetWrapper = {
  BrickAsset: number | null;
  ProceduralSize: IntVector;
};

export type BRInventoryEntryItem = {
  ItemType: number | null;
  bOverrideColors: boolean;
  MeshColors: Color[];
  DamageMultiplier: number;
  WeaponSpeedMultiplier: number;
  ItemScale: number;
  ItemNameOverride: string;
  ProjectileOverride: number | null;
};

export type BRPlayerPartCustomizationV3 = {
  PartDescriptor: number | null;
  DecalDescriptor: number | null;
  SocketName: string;
  Colors: Color[];
};

export type BRSavedComponentChunkSoA = {
  ComponentTypeCounters: BRSavedBrickComponentTypeCounter[];
  ComponentBrickIndices: number[];
  JointBrickIndices: number[];
  JointEntityReferences: number[];
  JointInitialRelativeOffsets: Vector3f[];
  JointInitialRelativeRotations: Quat4f[];
  MicrochipBrickIndices: number[];
  MicrochipBrickGridReferences: number[];
};

export type WireGraphLinearColorArray = {
  Values: LinearColor[];
};

export type WireGraphQuatArray = {
  Values: Quat[];
};

export type WireGraphRotatorArray = {
  Values: Rotator[];
};

export type WireGraphVectorArray = {
  Values: Vector[];
};

export type BRInventoryEntryBrick = {
  BrickType: BrickTypeNetWrapper;
};

export type BRInventoryEntryPlan = {
  Type: number;
  BrickTypeIfBrick: BrickTypeNetWrapper;
  EntityTypeIfEntity: number | null;
  ItemTypeIfItem: number | null;
};

export type BRPlayerAvatarCustomizationV3 = {
  Parts: BRPlayerPartCustomizationV3[];
};

export type BrickComponentData_BotSpawn = {
  RespawnTime: number;
  CorpseTimeout: number;
  GunSkill: number;
  Agression: number;
  ReactionTime: number;
  MovementRandomness: number;
  RunSpeed: number;
  HealthMultiplier: number;
  Jumpyness: number;
  MovementAmount: number;
  AttackMovementAmount: number;
  AggroRange: number;
  AttackDamageMultiplier: number;
  bCanJump: boolean;
  bBackVision: boolean;
  bVisionRaycasting: boolean;
  bCanTargetPlayers: boolean;
  bCanTargetBots: boolean;
  bActiveBot: boolean;
  bSpawnEnable: boolean;
  bDeleteBot: boolean;
  MoveTarget: Vector;
  MovementGoalDummy: BrickComponentWirePortControl_TeleportDestination;
  BotName: string;
  Skin: BRPlayerAvatarCustomizationV3;
  bColorsAreLinear: boolean;
  TeamCollisionChannel: number;
  bTeamCollision: boolean;
  bTeamCollision1: boolean;
  bTeamCollision2: boolean;
  bTeamCollision3: boolean;
  BotWeapon: number | null;
};

export type BrickComponentData_WireGraph_Exec_Character_SetInventoryEntry = {
  Slot: number;
  Entry: BRInventoryEntryConfig;
  EntryPlan: BRInventoryEntryPlan;
};

/** Component type name -> data struct shape, for editor completion. */
export type ComponentTypeDataMap = {
  BrickComponentType_Internal_CharacterZoneEvent_Entered: BrickComponentData_Internal_CharacterZoneEvent;
  BrickComponentType_Internal_CharacterZoneEvent_Left: BrickComponentData_Internal_CharacterZoneEvent;
  BrickComponentType_Internal_EntityZoneEvent_Entered: BrickComponentData_Internal_EntityZoneEvent;
  BrickComponentType_Internal_EntityZoneEvent_Left: BrickComponentData_Internal_EntityZoneEvent;
  BrickComponentType_Internal_MicrochipInput: BrickComponentData_Internal_MicrochipInput;
  BrickComponentType_Internal_MicrochipOutput: BrickComponentData_Internal_MicrochipOutput;
  BrickComponentType_Internal_ProjectileZoneEvent_Entered: BrickComponentData_Internal_ProjectileZoneEvent;
  BrickComponentType_Internal_ProjectileZoneEvent_Left: BrickComponentData_Internal_ProjectileZoneEvent;
  BrickComponentType_Internal_ReadBrickGrid: BrickComponentData_Internal_ReadBrickGrid;
  BrickComponentType_Internal_TeleportDestination: BrickComponentData_TeleportDestination;
  BrickComponentType_Internal_ZoneEvent_BrickChanged: BrickComponentData_Internal_ZoneEvent;
  BrickComponentType_Internal_ZoneEvent_BrickRemoved: BrickComponentData_Internal_ZoneEvent;
  BrickComponentType_PrefabSpawn: BrickComponentData_PrefabSpawn;
  BrickComponentType_WireGraphPseudo_ArrayVar: BrickComponentData_WireGraphPseudo_ArrayVar;
  BrickComponentType_WireGraphPseudo_BufferSeconds: BrickComponentData_WireGraphPseudo_BufferSeconds;
  BrickComponentType_WireGraphPseudo_BufferTicks: BrickComponentData_WireGraphPseudo_BufferTicks;
  BrickComponentType_WireGraphPseudo_Dampen: BrickComponentData_WireGraphPseudo_Dampen;
  BrickComponentType_WireGraphPseudo_QueueSeconds: BrickComponentData_WireGraphPseudo_QueueSeconds;
  BrickComponentType_WireGraphPseudo_QueueTicks: BrickComponentData_WireGraphPseudo_QueueTicks;
  BrickComponentType_WireGraphPseudo_Timer: BrickComponentData_WireGraphPseudo_Timer;
  BrickComponentType_WireGraphPseudo_Tween: BrickComponentData_WireGraphPseudo_Tween;
  BrickComponentType_WireGraphPseudo_Var: BrickComponentData_WireGraphPseudo_Var;
  BrickComponentType_WireGraph_AudioReference: BrickComponentData_WireGraph_AudioReference;
  BrickComponentType_WireGraph_BrickAssetReference: BrickComponentData_WireGraph_BrickAssetReference;
  BrickComponentType_WireGraph_DeltaTime: BrickComponentData_WireGraph_DeltaTime;
  BrickComponentType_WireGraph_EntityTypeReference: BrickComponentData_WireGraph_EntityTypeReference;
  BrickComponentType_WireGraph_Exec_ArrayVar_Append: BrickComponentData_WireGraph_Exec_ArrayVar_DualRef;
  BrickComponentType_WireGraph_Exec_ArrayVar_Average: BrickComponentData_WireGraph_Exec_ArrayVar_Average;
  BrickComponentType_WireGraph_Exec_ArrayVar_Clear: BrickComponentData_WireGraph_Exec_ArrayVar_Base;
  BrickComponentType_WireGraph_Exec_ArrayVar_CopyFrom: BrickComponentData_WireGraph_Exec_ArrayVar_DualRef;
  BrickComponentType_WireGraph_Exec_ArrayVar_Fill: BrickComponentData_WireGraph_Exec_ArrayVar_Push;
  BrickComponentType_WireGraph_Exec_ArrayVar_Find: BrickComponentData_WireGraph_Exec_ArrayVar_Find;
  BrickComponentType_WireGraph_Exec_ArrayVar_Get: BrickComponentData_WireGraph_Exec_ArrayVar_Get;
  BrickComponentType_WireGraph_Exec_ArrayVar_GetLength: BrickComponentData_WireGraph_Exec_ArrayVar_GetLength;
  BrickComponentType_WireGraph_Exec_ArrayVar_Insert: BrickComponentData_WireGraph_Exec_ArrayVar_Insert;
  BrickComponentType_WireGraph_Exec_ArrayVar_Max: BrickComponentData_WireGraph_Exec_ArrayVar_MinMax;
  BrickComponentType_WireGraph_Exec_ArrayVar_Min: BrickComponentData_WireGraph_Exec_ArrayVar_MinMax;
  BrickComponentType_WireGraph_Exec_ArrayVar_Pop: BrickComponentData_WireGraph_Exec_ArrayVar_Pop;
  BrickComponentType_WireGraph_Exec_ArrayVar_Push: BrickComponentData_WireGraph_Exec_ArrayVar_Push;
  BrickComponentType_WireGraph_Exec_ArrayVar_RemoveAtIndex: BrickComponentData_WireGraph_Exec_ArrayVar_RemoveAtIndex;
  BrickComponentType_WireGraph_Exec_ArrayVar_Resize: BrickComponentData_WireGraph_Exec_ArrayVar_Resize;
  BrickComponentType_WireGraph_Exec_ArrayVar_Reverse: BrickComponentData_WireGraph_Exec_ArrayVar_Base;
  BrickComponentType_WireGraph_Exec_ArrayVar_SetAtIndex: BrickComponentData_WireGraph_Exec_ArrayVar_ElementOp;
  BrickComponentType_WireGraph_Exec_ArrayVar_Shuffle: BrickComponentData_WireGraph_Exec_ArrayVar_Base;
  BrickComponentType_WireGraph_Exec_ArrayVar_Slice: BrickComponentData_WireGraph_Exec_ArrayVar_Slice;
  BrickComponentType_WireGraph_Exec_ArrayVar_Sort: BrickComponentData_WireGraph_Exec_ArrayVar_Sort;
  BrickComponentType_WireGraph_Exec_ArrayVar_Sum: BrickComponentData_WireGraph_Exec_ArrayVar_Sum;
  BrickComponentType_WireGraph_Exec_ArrayVar_Swap: BrickComponentData_WireGraph_Exec_ArrayVar_Swap;
  BrickComponentType_WireGraph_Exec_Branch: BrickComponentData_WireGraph_ExecBranch;
  BrickComponentType_WireGraph_Exec_Character_AddInventoryBrick: BrickComponentData_WireGraph_Exec_Character_AddInventoryBrick;
  BrickComponentType_WireGraph_Exec_Character_AddInventoryEntity: BrickComponentData_WireGraph_Exec_Character_AddInventoryEntity;
  BrickComponentType_WireGraph_Exec_Character_AddInventoryEntry: BrickComponentData_WireGraph_Exec_Character_AddInventoryEntry;
  BrickComponentType_WireGraph_Exec_Character_AddInventoryItem: BrickComponentData_WireGraph_Exec_Character_AddInventoryItem;
  BrickComponentType_WireGraph_Exec_Character_AddInventoryItemAdv: BrickComponentData_WireGraph_Exec_Character_AddInventoryItemAdv;
  BrickComponentType_WireGraph_Exec_Character_GetAim: BrickComponentData_WireGraph_Exec_Character_GetAim;
  BrickComponentType_WireGraph_Exec_Character_GetDamage: BrickComponentData_WireGraph_Exec_Character_GetDamage;
  BrickComponentType_WireGraph_Exec_Character_GetFromController: BrickComponentData_WireGraph_Exec_Character_GetFromController;
  BrickComponentType_WireGraph_Exec_Character_IncDamage: BrickComponentData_WireGraph_Exec_Character_IncDamage;
  BrickComponentType_WireGraph_Exec_Character_SetDamage: BrickComponentData_WireGraph_Exec_Character_SetDamage;
  BrickComponentType_WireGraph_Exec_Character_SetInventoryBrick: BrickComponentData_WireGraph_Exec_Character_SetInventoryBrick;
  BrickComponentType_WireGraph_Exec_Character_SetInventoryEntity: BrickComponentData_WireGraph_Exec_Character_SetInventoryEntity;
  BrickComponentType_WireGraph_Exec_Character_SetInventoryEntry: BrickComponentData_WireGraph_Exec_Character_SetInventoryEntry;
  BrickComponentType_WireGraph_Exec_Character_SetInventoryItem: BrickComponentData_WireGraph_Exec_Character_SetInventoryItem;
  BrickComponentType_WireGraph_Exec_Character_SetInventoryItemAdv: BrickComponentData_WireGraph_Exec_Character_SetInventoryItemAdv;
  BrickComponentType_WireGraph_Exec_Character_SetTempPermission: BrickComponentData_WireGraph_Exec_Character_SetTempPermission;
  BrickComponentType_WireGraph_Exec_Character_ShowHint: BrickComponentData_WireGraph_Exec_Character_ShowHint;
  BrickComponentType_WireGraph_Exec_ChatCommand: BrickComponentData_WireGraph_Exec_ChatCommand;
  BrickComponentType_WireGraph_Exec_Controller_DisplayText: BrickComponentData_WireGraph_Exec_Controller_DisplayText;
  BrickComponentType_WireGraph_Exec_Controller_GetDisplayName: BrickComponentData_WireGraph_Exec_Controller_GetDisplayName;
  BrickComponentType_WireGraph_Exec_Controller_GetFromEntity: BrickComponentData_WireGraph_Exec_Controller_GetFromEntity;
  BrickComponentType_WireGraph_Exec_Controller_GetUserId: BrickComponentData_WireGraph_Exec_Controller_GetUserId;
  BrickComponentType_WireGraph_Exec_Controller_GetUserName: BrickComponentData_WireGraph_Exec_Controller_GetUserName;
  BrickComponentType_WireGraph_Exec_Controller_HasPermission: BrickComponentData_WireGraph_Exec_Controller_HasPermission;
  BrickComponentType_WireGraph_Exec_Controller_HasRole: BrickComponentData_WireGraph_Exec_Controller_HasRole;
  BrickComponentType_WireGraph_Exec_Controller_IsTrustedByBrickOwner: BrickComponentData_WireGraph_Exec_Controller_IsTrustedByBrickOwner;
  BrickComponentType_WireGraph_Exec_Controller_SetCanRespawn: BrickComponentData_WireGraph_Exec_Controller_SetCanRespawn;
  BrickComponentType_WireGraph_Exec_Controller_ShowChatMessage: BrickComponentData_WireGraph_Exec_Controller_ShowChatMessage;
  BrickComponentType_WireGraph_Exec_Controller_ShowMessageBox: BrickComponentData_WireGraph_Exec_Controller_ShowMessageBox;
  BrickComponentType_WireGraph_Exec_Controller_ShowStatusMessage: BrickComponentData_WireGraph_Exec_Controller_ShowStatusMessage;
  BrickComponentType_WireGraph_Exec_Cycle: BrickComponentData_WireGraph_Exec_Cycle;
  BrickComponentType_WireGraph_Exec_Entity_AddLocationRotation: BrickComponentData_WireGraph_Exec_Entity_AddLocationRotation;
  BrickComponentType_WireGraph_Exec_Entity_AddVelocity: BrickComponentData_WireGraph_Exec_Entity_AddVelocity;
  BrickComponentType_WireGraph_Exec_Entity_GetAngularVelocity: BrickComponentData_WireGraph_Exec_Entity_GetAngularVelocity;
  BrickComponentType_WireGraph_Exec_Entity_GetLinearVelocity: BrickComponentData_WireGraph_Exec_Entity_GetLinearVelocity;
  BrickComponentType_WireGraph_Exec_Entity_GetLocation: BrickComponentData_WireGraph_Exec_Entity_GetLocation;
  BrickComponentType_WireGraph_Exec_Entity_GetLocationRotation: BrickComponentData_WireGraph_Exec_Entity_GetLocationRotation;
  BrickComponentType_WireGraph_Exec_Entity_GetRotation: BrickComponentData_WireGraph_Exec_Entity_GetRotation;
  BrickComponentType_WireGraph_Exec_Entity_GetTag: BrickComponentData_WireGraph_Exec_Entity_GetTag;
  BrickComponentType_WireGraph_Exec_Entity_GetVelocity: BrickComponentData_WireGraph_Exec_Entity_GetVelocity;
  BrickComponentType_WireGraph_Exec_Entity_RelativeTeleport: BrickComponentData_WireGraph_Exec_Entity_RelativeTeleport;
  BrickComponentType_WireGraph_Exec_Entity_SetAngularVelocity: BrickComponentData_WireGraph_Exec_Entity_SetAngularVelocity;
  BrickComponentType_WireGraph_Exec_Entity_SetFrozen: BrickComponentData_WireGraph_Exec_Entity_SetFrozen;
  BrickComponentType_WireGraph_Exec_Entity_SetGravityDirection: BrickComponentData_WireGraph_Exec_Entity_SetGravityDirection;
  BrickComponentType_WireGraph_Exec_Entity_SetLinearVelocity: BrickComponentData_WireGraph_Exec_Entity_SetLinearVelocity;
  BrickComponentType_WireGraph_Exec_Entity_SetLocation: BrickComponentData_WireGraph_Exec_Entity_SetLocation;
  BrickComponentType_WireGraph_Exec_Entity_SetLocationRotation: BrickComponentData_WireGraph_Exec_Entity_SetLocationRotation;
  BrickComponentType_WireGraph_Exec_Entity_SetRotation: BrickComponentData_WireGraph_Exec_Entity_SetRotation;
  BrickComponentType_WireGraph_Exec_Entity_SetTag: BrickComponentData_WireGraph_Exec_Entity_SetTag;
  BrickComponentType_WireGraph_Exec_Entity_SetVelocity: BrickComponentData_WireGraph_Exec_Entity_SetVelocity;
  BrickComponentType_WireGraph_Exec_Entity_Teleport: BrickComponentData_WireGraph_Exec_Entity_Teleport;
  BrickComponentType_WireGraph_Exec_Gamemode_BroadcastChatMessage: BrickComponentData_WireGraph_Exec_Gamemode_BroadcastChatMessage;
  BrickComponentType_WireGraph_Exec_Gamemode_BroadcastStatusMessage: BrickComponentData_WireGraph_Exec_Gamemode_BroadcastStatusMessage;
  BrickComponentType_WireGraph_Exec_Gamemode_FillArrayFromPlayers: BrickComponentData_WireGraph_Exec_ArrayVar_Base;
  BrickComponentType_WireGraph_Exec_Gamemode_FillArrayFromTeamMembers: BrickComponentData_WireGraph_Exec_Gamemode_FillArrayFromTeamMembers;
  BrickComponentType_WireGraph_Exec_Gamemode_GetCurrentRound: BrickComponentData_WireGraph_Exec_Gamemode_GetCurrentRound;
  BrickComponentType_WireGraph_Exec_Gamemode_GetLeaderboardValue: BrickComponentData_WireGraph_Exec_Gamemode_GetLeaderboardValue;
  BrickComponentType_WireGraph_Exec_Gamemode_GetTeam: BrickComponentData_WireGraph_Exec_Gamemode_GetTeam;
  BrickComponentType_WireGraph_Exec_Gamemode_GetTeamByName: BrickComponentData_WireGraph_Exec_Gamemode_GetTeamByName;
  BrickComponentType_WireGraph_Exec_Gamemode_GetTeamLeaderboardValue: BrickComponentData_WireGraph_Exec_Gamemode_GetTeamLeaderboardValue;
  BrickComponentType_WireGraph_Exec_Gamemode_GetTeamName: BrickComponentData_WireGraph_Exec_Gamemode_GetTeamName;
  BrickComponentType_WireGraph_Exec_Gamemode_IncrementLeaderboardValue: BrickComponentData_WireGraph_Exec_Gamemode_LeaderboardValue;
  BrickComponentType_WireGraph_Exec_Gamemode_IncrementTeamLeaderboardValue: BrickComponentData_WireGraph_Exec_Gamemode_TeamLeaderboardValue;
  BrickComponentType_WireGraph_Exec_Gamemode_PlayerWins: BrickComponentData_WireGraph_Exec_Gamemode_PlayerWins;
  BrickComponentType_WireGraph_Exec_Gamemode_SetLeaderboardValue: BrickComponentData_WireGraph_Exec_Gamemode_LeaderboardValue;
  BrickComponentType_WireGraph_Exec_Gamemode_SetTeam: BrickComponentData_WireGraph_Exec_Gamemode_SetTeam;
  BrickComponentType_WireGraph_Exec_Gamemode_SetTeamLeaderboardValue: BrickComponentData_WireGraph_Exec_Gamemode_TeamLeaderboardValue;
  BrickComponentType_WireGraph_Exec_Gamemode_SetTeamPinned: BrickComponentData_WireGraph_Exec_Gamemode_SetTeamPinned;
  BrickComponentType_WireGraph_Exec_Gamemode_TeamWins: BrickComponentData_WireGraph_Exec_Gamemode_TeamWins;
  BrickComponentType_WireGraph_Exec_PlayGlobalAudio: BrickComponentData_WireGraph_Exec_PlayGlobalAudio;
  BrickComponentType_WireGraph_Exec_PrefabSpawner: BrickComponentData_WireGraph_Exec_PrefabSpawner;
  BrickComponentType_WireGraph_Exec_PrintToConsole: BrickComponentData_WireGraph_Exec_PrintToConsole;
  BrickComponentType_WireGraph_Exec_Random: BrickComponentData_WireGraph_Exec_Random;
  BrickComponentType_WireGraph_Exec_Sweep: BrickComponentData_WireGraph_Exec_Sweep;
  BrickComponentType_WireGraph_Exec_Toggle: BrickComponentData_WireGraph_Exec_Toggle;
  BrickComponentType_WireGraph_Exec_Union: BrickComponentData_WireGraph_ExecUnion;
  BrickComponentType_WireGraph_Exec_Var_Get: BrickComponentData_WireGraph_Exec_Var_Get;
  BrickComponentType_WireGraph_Exec_Var_Increment: BrickComponentData_WireGraph_Exec_Var_EditOrGet;
  BrickComponentType_WireGraph_Exec_Var_Set: BrickComponentData_WireGraph_Exec_Var_EditOrGet;
  BrickComponentType_WireGraph_Expr_BitwiseAND: BrickComponentData_WireGraph_Expr_IntInt_Int;
  BrickComponentType_WireGraph_Expr_BitwiseBitCount: BrickComponentData_WireGraph_Expr_Int_Int;
  BrickComponentType_WireGraph_Expr_BitwiseNAND: BrickComponentData_WireGraph_Expr_IntInt_Int;
  BrickComponentType_WireGraph_Expr_BitwiseNOR: BrickComponentData_WireGraph_Expr_IntInt_Int;
  BrickComponentType_WireGraph_Expr_BitwiseNOT: BrickComponentData_WireGraph_Expr_Int_Int;
  BrickComponentType_WireGraph_Expr_BitwiseOR: BrickComponentData_WireGraph_Expr_IntInt_Int;
  BrickComponentType_WireGraph_Expr_BitwiseShiftLeft: BrickComponentData_WireGraph_Expr_IntInt_Int;
  BrickComponentType_WireGraph_Expr_BitwiseShiftRight: BrickComponentData_WireGraph_Expr_IntInt_Int;
  BrickComponentType_WireGraph_Expr_BitwiseXOR: BrickComponentData_WireGraph_Expr_IntInt_Int;
  BrickComponentType_WireGraph_Expr_Ceil: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_ChangeDetector: BrickComponentData_WireGraph_Expr_ChangeDetector;
  BrickComponentType_WireGraph_Expr_ChangeDetectorExec: BrickComponentData_WireGraph_Expr_ChangeDetectorExec;
  BrickComponentType_WireGraph_Expr_ColorBlend: BrickComponentData_WireGraph_Expr_ColorBlend;
  BrickComponentType_WireGraph_Expr_ColorConvert: BrickComponentData_WireGraph_Expr_ColorConvert;
  BrickComponentType_WireGraph_Expr_ColorToHex: BrickComponentData_WireGraph_Expr_ColorToHex;
  BrickComponentType_WireGraph_Expr_CompareEqual: BrickComponentData_WireGraph_Expr_Compare;
  BrickComponentType_WireGraph_Expr_CompareGreater: BrickComponentData_WireGraph_Expr_MathCompare;
  BrickComponentType_WireGraph_Expr_CompareGreaterOrEqual: BrickComponentData_WireGraph_Expr_MathCompare;
  BrickComponentType_WireGraph_Expr_CompareLess: BrickComponentData_WireGraph_Expr_MathCompare;
  BrickComponentType_WireGraph_Expr_CompareLessOrEqual: BrickComponentData_WireGraph_Expr_MathCompare;
  BrickComponentType_WireGraph_Expr_CompareNotEqual: BrickComponentData_WireGraph_Expr_Compare;
  BrickComponentType_WireGraph_Expr_Convert: BrickComponentData_WireGraph_Expr_Convert;
  BrickComponentType_WireGraph_Expr_DirectionToRotation: BrickComponentData_WireGraph_Expr_DirectionToRotation;
  BrickComponentType_WireGraph_Expr_EdgeDetector: BrickComponentData_WireGraph_Expr_EdgeDetector;
  BrickComponentType_WireGraph_Expr_EdgeDetectorExec: BrickComponentData_WireGraph_Expr_EdgeDetectorExec;
  BrickComponentType_WireGraph_Expr_Floor: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_InvertRotation: BrickComponentData_WireGraph_Expr_InvertRotation;
  BrickComponentType_WireGraph_Expr_LogicalAND: BrickComponentData_WireGraph_Expr_BoolBool_Bool;
  BrickComponentType_WireGraph_Expr_LogicalNAND: BrickComponentData_WireGraph_Expr_BoolBool_Bool;
  BrickComponentType_WireGraph_Expr_LogicalNOR: BrickComponentData_WireGraph_Expr_BoolBool_Bool;
  BrickComponentType_WireGraph_Expr_LogicalNOT: BrickComponentData_WireGraph_Expr_Bool_Bool;
  BrickComponentType_WireGraph_Expr_LogicalOR: BrickComponentData_WireGraph_Expr_BoolBool_Bool;
  BrickComponentType_WireGraph_Expr_LogicalXOR: BrickComponentData_WireGraph_Expr_BoolBool_Bool;
  BrickComponentType_WireGraph_Expr_MakeColor: BrickComponentData_WireGraph_Expr_MakeColor;
  BrickComponentType_WireGraph_Expr_MakeColorHex: BrickComponentData_WireGraph_Expr_MakeColorHex;
  BrickComponentType_WireGraph_Expr_MakeColorSRGB: BrickComponentData_WireGraph_Expr_MakeColorSRGB;
  BrickComponentType_WireGraph_Expr_MakeQuaternion: BrickComponentData_WireGraph_Expr_MakeQuaternion;
  BrickComponentType_WireGraph_Expr_MakeRotation: BrickComponentData_WireGraph_Expr_MakeRotation;
  BrickComponentType_WireGraph_Expr_MakeVector: BrickComponentData_WireGraph_Expr_MakeVector;
  BrickComponentType_WireGraph_Expr_MathAbs: BrickComponentData_WireGraph_Expr_PrimMathVariant_PrimMathVariant;
  BrickComponentType_WireGraph_Expr_MathAcos: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathAcosh: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathAdd: BrickComponentData_WireGraph_Expr_PrimMathVariantPrimMathVariant_PrimMathVariant;
  BrickComponentType_WireGraph_Expr_MathAsin: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathAsinh: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathAtan: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathAtan2: BrickComponentData_WireGraph_Expr_MathAtan2;
  BrickComponentType_WireGraph_Expr_MathAtanh: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathBlend: BrickComponentData_WireGraph_Expr_MathBlend;
  BrickComponentType_WireGraph_Expr_MathClamp: BrickComponentData_WireGraph_Expr_MathClamp;
  BrickComponentType_WireGraph_Expr_MathCos: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathCosh: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathDegreesToRadians: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathDivide: BrickComponentData_WireGraph_Expr_PrimMathVariantPrimMathVariant_PrimMathVariant;
  BrickComponentType_WireGraph_Expr_MathEasing: BrickComponentData_WireGraph_Expr_MathEasing;
  BrickComponentType_WireGraph_Expr_MathExp: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathLn: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathLogBase: BrickComponentData_WireGraph_Expr_MathLogBase;
  BrickComponentType_WireGraph_Expr_MathMax: BrickComponentData_WireGraph_Expr_PrimMathVariantPrimMathVariant_PrimMathVariant;
  BrickComponentType_WireGraph_Expr_MathMin: BrickComponentData_WireGraph_Expr_PrimMathVariantPrimMathVariant_PrimMathVariant;
  BrickComponentType_WireGraph_Expr_MathModulo: BrickComponentData_WireGraph_Expr_PrimMathVariantPrimMathVariant_PrimMathVariant;
  BrickComponentType_WireGraph_Expr_MathModuloFloored: BrickComponentData_WireGraph_Expr_PrimMathVariantPrimMathVariant_PrimMathVariant;
  BrickComponentType_WireGraph_Expr_MathMultiply: BrickComponentData_WireGraph_Expr_PrimMathVariantPrimMathVariant_PrimMathVariant;
  BrickComponentType_WireGraph_Expr_MathNegate: BrickComponentData_WireGraph_Expr_Variant_Variant;
  BrickComponentType_WireGraph_Expr_MathPow: BrickComponentData_WireGraph_Expr_MathPow;
  BrickComponentType_WireGraph_Expr_MathRadiansToDegrees: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathSign: BrickComponentData_WireGraph_Expr_PrimMathVariant_PrimMathVariant;
  BrickComponentType_WireGraph_Expr_MathSin: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathSinh: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathSqrt: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathSubtract: BrickComponentData_WireGraph_Expr_PrimMathVariantPrimMathVariant_PrimMathVariant;
  BrickComponentType_WireGraph_Expr_MathTan: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_MathTanh: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_NearlyEqual: BrickComponentData_WireGraph_Expr_NearlyEqual;
  BrickComponentType_WireGraph_Expr_QuatAngleBetween: BrickComponentData_WireGraph_Expr_QuatAngleBetween;
  BrickComponentType_WireGraph_Expr_QuatBetween: BrickComponentData_WireGraph_Expr_QuatBetween;
  BrickComponentType_WireGraph_Expr_QuatDotProduct: BrickComponentData_WireGraph_Expr_QuatDotProduct;
  BrickComponentType_WireGraph_Expr_QuatFromAxisAngle: BrickComponentData_WireGraph_Expr_QuatFromAxisAngle;
  BrickComponentType_WireGraph_Expr_QuatSlerp: BrickComponentData_WireGraph_Expr_QuatSlerp;
  BrickComponentType_WireGraph_Expr_QuatToAxisAngle: BrickComponentData_WireGraph_Expr_QuatToAxisAngle;
  BrickComponentType_WireGraph_Expr_RotateVector: BrickComponentData_WireGraph_Expr_RotateVector;
  BrickComponentType_WireGraph_Expr_RotationToDirection: BrickComponentData_WireGraph_Expr_RotationToDirection;
  BrickComponentType_WireGraph_Expr_Round: BrickComponentData_WireGraph_Expr_Float_Float;
  BrickComponentType_WireGraph_Expr_Select: BrickComponentData_WireGraph_Expr_Select;
  BrickComponentType_WireGraph_Expr_SplitColor: BrickComponentData_WireGraph_Expr_SplitColor;
  BrickComponentType_WireGraph_Expr_SplitColorSRGB: BrickComponentData_WireGraph_Expr_SplitColorSRGB;
  BrickComponentType_WireGraph_Expr_SplitQuaternion: BrickComponentData_WireGraph_Expr_SplitQuaternion;
  BrickComponentType_WireGraph_Expr_SplitRotation: BrickComponentData_WireGraph_Expr_SplitRotation;
  BrickComponentType_WireGraph_Expr_SplitVector: BrickComponentData_WireGraph_Expr_SplitVector;
  BrickComponentType_WireGraph_Expr_String_Concatenate: BrickComponentData_WireGraph_Expr_String_Concatenate;
  BrickComponentType_WireGraph_Expr_String_Contains: BrickComponentData_WireGraph_Expr_String_Contains;
  BrickComponentType_WireGraph_Expr_String_EndsWith: BrickComponentData_WireGraph_Expr_String_EndsWith;
  BrickComponentType_WireGraph_Expr_String_Find: BrickComponentData_WireGraph_Expr_String_Find;
  BrickComponentType_WireGraph_Expr_String_FormatText: BrickComponentData_WireGraph_Expr_String_FormatText;
  BrickComponentType_WireGraph_Expr_String_Length: BrickComponentData_WireGraph_Expr_String_Length;
  BrickComponentType_WireGraph_Expr_String_ParseInt: BrickComponentData_WireGraph_Expr_String_ParseInt;
  BrickComponentType_WireGraph_Expr_String_ParseNumber: BrickComponentData_WireGraph_Expr_String_ParseNumber;
  BrickComponentType_WireGraph_Expr_String_Replace: BrickComponentData_WireGraph_Expr_String_Replace;
  BrickComponentType_WireGraph_Expr_String_Split: BrickComponentData_WireGraph_Expr_String_Split;
  BrickComponentType_WireGraph_Expr_String_StartsWith: BrickComponentData_WireGraph_Expr_String_StartsWith;
  BrickComponentType_WireGraph_Expr_String_Substring: BrickComponentData_WireGraph_Expr_String_Substring;
  BrickComponentType_WireGraph_Expr_String_ToLower: BrickComponentData_WireGraph_Expr_String_ToLower;
  BrickComponentType_WireGraph_Expr_String_ToUpper: BrickComponentData_WireGraph_Expr_String_ToUpper;
  BrickComponentType_WireGraph_Expr_String_Trim: BrickComponentData_WireGraph_Expr_String_Trim;
  BrickComponentType_WireGraph_Expr_Swap: BrickComponentData_WireGraph_Expr_Swap;
  BrickComponentType_WireGraph_Expr_VecCrossProduct: BrickComponentData_WireGraph_Expr_VecVec_Vec;
  BrickComponentType_WireGraph_Expr_VecDistance: BrickComponentData_WireGraph_Expr_VecVec_Float;
  BrickComponentType_WireGraph_Expr_VecDistanceSquared: BrickComponentData_WireGraph_Expr_VecVec_Float;
  BrickComponentType_WireGraph_Expr_VecDotProduct: BrickComponentData_WireGraph_Expr_VecVec_Float;
  BrickComponentType_WireGraph_Expr_VecMagnitude: BrickComponentData_WireGraph_Expr_Vec_Float;
  BrickComponentType_WireGraph_Expr_VecMagnitudeSquared: BrickComponentData_WireGraph_Expr_Vec_Float;
  BrickComponentType_WireGraph_Expr_VecNormalize: BrickComponentData_WireGraph_Expr_Vec_Vec;
  BrickComponentType_WireGraph_Expr_VecScale: BrickComponentData_WireGraph_Expr_VecFloat_Vec;
  BrickComponentType_WireGraph_Fake_Gamemode_CharacterDamagedEvent: BrickComponentData_WireGraph_Fake_CharacterDamageEvent;
  BrickComponentType_WireGraph_Fake_Gamemode_CharacterDiedEvent: BrickComponentData_WireGraph_Fake_CharacterDeathEvent;
  BrickComponentType_WireGraph_Fake_Gamemode_CharacterSpawnedEvent: BrickComponentData_WireGraph_Fake_CharacterEvent;
  BrickComponentType_WireGraph_Fake_Gamemode_ControllerJoinedEvent: BrickComponentData_WireGraph_Fake_ControllerEvent;
  BrickComponentType_WireGraph_Fake_Gamemode_ControllerLeftEvent: BrickComponentData_WireGraph_Fake_ControllerEvent;
  BrickComponentType_WireGraph_Fake_Gamemode_RoundEndEvent: BrickComponentData_WireGraph_Fake_RoundEvent;
  BrickComponentType_WireGraph_Fake_Gamemode_RoundStartEvent: BrickComponentData_WireGraph_Fake_RoundEvent;
  BrickComponentType_WireGraph_FindPlayer: BrickComponentData_WireGraph_FindPlayer;
  BrickComponentType_WireGraph_FontReference: BrickComponentData_WireGraph_FontReference;
  BrickComponentType_WireGraph_ItemReference: BrickComponentData_WireGraph_ItemReference;
  BrickComponentType_WireGraph_OneShotAudioReference: BrickComponentData_WireGraph_OneShotAudioReference;
  BrickComponentType_WireGraph_ParticleReference: BrickComponentData_WireGraph_ParticleReference;
  BrickComponentType_WireGraph_PickupReference: BrickComponentData_WireGraph_PickupReference;
  BrickComponentType_WireGraph_ProjectileReference: BrickComponentData_WireGraph_ProjectileReference;
  BrickComponentType_WireGraph_ServerUptime: BrickComponentData_WireGraph_ServerUptime;
  BrickComponentType_WireGraph_WheelEngineAudioReference: BrickComponentData_WireGraph_WheelEngineAudioReference;
  Component_AudioEmitter: BrickComponentData_AudioEmitter;
  Component_BotSpawn: BrickComponentData_BotSpawn;
  Component_BrickPropertyChanger: BrickComponentData_BrickPropertyChanger;
  Component_Button: BrickComponentData_Button;
  Component_CheckPoint: BrickComponentData_CheckPoint;
  Component_Damage: BrickComponentData_Damage;
  Component_Interact: BrickComponentData_Interact;
  Component_Internal_AnimatedButton: BrickComponentData_Button;
  Component_Internal_AnimatedPressurePlate: BrickComponentData_Touch;
  Component_Internal_AnimatedSwitch: BrickComponentData_Switch;
  Component_Internal_AttachedZone: BrickComponentData_Internal_AttachedZone;
  Component_Internal_Bearing: BrickComponentData_Bearing;
  Component_Internal_Gyroscope: BrickComponentData_Gyroscope;
  Component_Internal_InputSplitter: BrickComponentData_Internal_InputSplitter_V2;
  Component_Internal_Joint_Wheel: BrickComponentData_Joint_Wheel;
  Component_Internal_Joint_Wheel_Suspension: BrickComponentData_Joint_Wheel_Suspension;
  Component_Internal_Microchip: BrickComponentData_Internal_Microchip;
  Component_Internal_Motor: BrickComponentData_Motor;
  Component_Internal_MotorSlider: BrickComponentData_MotorSlider;
  Component_Internal_ProjectileSpawner_Cannon: BrickComponentData_ProjectileSpawner;
  Component_Internal_Rerouter: BrickComponentData_Rerouter;
  Component_Internal_RigidBearing: BrickComponentData_RigidBearing;
  Component_Internal_RigidSlider: BrickComponentData_RigidSlider;
  Component_Internal_Seat: BrickComponentData_Seat_V2;
  Component_Internal_Servo: BrickComponentData_Servo;
  Component_Internal_ServoSlider: BrickComponentData_ServoSlider;
  Component_Internal_Slider: BrickComponentData_Slider;
  Component_Internal_Thruster: BrickComponentData_Thruster;
  Component_Internal_WeightBrick: BrickComponentData_WeightBrick;
  Component_Internal_WheelEngine: BrickComponentData_WheelEngine_V2;
  Component_ItemSpawn: BrickComponentData_ItemSpawn;
  Component_OneShotAudioEmitter: BrickComponentData_OneShotAudioEmitter;
  Component_PointLight: BrickComponentData_PointLight;
  Component_ProjectileSpawner: BrickComponentData_ProjectileSpawner;
  Component_SpawnPoint: BrickComponentData_SpawnPoint;
  Component_SpotLight: BrickComponentData_SpotLight;
  Component_Switch: BrickComponentData_Switch;
  Component_Target: BrickComponentData_Target;
  Component_TextDisplay: BrickComponentData_TextDisplay;
  Component_Touch: BrickComponentData_Touch;
  Component_WireGraph_PlayAudioAt: BrickComponentData_WireGraph_Exec_Entity_PlayAudioAt;
};

/** Every known component type name. */
export type BrdbComponentTypeName = keyof ComponentTypeDataMap;
