// Regenerates src/brdb/schemas.ts and src/brdb/catalog.ts from a crate checkout.
// Usage: node scripts/syncBrdbData.mjs [path-to-brdb-crate-checkout]
//
// Schemas are parsed HERE, at generation time, and emitted as plain object
// literals — the runtime hydrates data instead of parsing schema text. This
// parser is the generation-time twin of src/brdb/schemaText.ts; any drift
// between them is caught by the schema byte-gate tests (embedded schema ->
// binary must equal the crate-serialized fixtures).
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const crate = join(process.argv[2] ?? '../brdb', 'crates/brdb');

// --- plaintext schema parser (generation-time only) ---

const IDENT = String.raw`[A-Za-z_]\w*(?:::\w+)*`;
const enumEntryRe = new RegExp(
  String.raw`^(${IDENT})\s*=\s*(-?\d+(?:_\d+)*|0b[01]+(?:_[01]+)*|0x[0-9a-fA-F]+(?:_[0-9a-fA-F]+)*)$`
);
const memberRe = new RegExp(String.raw`^${IDENT}$`);
const propRe = new RegExp(
  String.raw`^(\w+)\s*:\s*(\w+)\s*(\[\s*(flat)?\s*\])?$`
);

const stripComments = text =>
  text
    .replace(/\/\*[\s\S]*?\*\//g, ' ')
    .replace(/\/\/[^\n]*/g, ' ')
    .replace(/#[^\n]*/g, ' ');

const parseIntLiteral = raw => {
  const t = raw.replace(/_/g, '');
  if (t.startsWith('0b')) return parseInt(t.slice(2), 2);
  if (t.startsWith('0x')) return parseInt(t.slice(2), 16);
  return parseInt(t, 10);
};

function parseSchema(text, file) {
  const src = stripComments(text);
  const out = { enums: {}, variants: {}, structs: {} };
  const declRe = /\b(enum|variant|struct)\s+([A-Za-z0-9_]+)\s*\{([^{}]*)\}/g;
  let lastEnd = 0;
  let match;
  while ((match = declRe.exec(src))) {
    if (src.slice(lastEnd, match.index).trim() !== '')
      throw new Error(`${file}: unexpected text before ${match[2]}`);
    lastEnd = declRe.lastIndex;
    const [, keyword, name, body] = match;
    const items = body
      .split(',')
      .map(s => s.trim())
      .filter(s => s !== '');
    if (keyword === 'enum') {
      const values = {};
      for (const item of items) {
        const m = enumEntryRe.exec(item);
        if (!m) throw new Error(`${file}: bad enum entry '${item}' in ${name}`);
        values[m[1]] = parseIntLiteral(m[2]);
      }
      out.enums[name] = values;
    } else if (keyword === 'variant') {
      for (const item of items)
        if (!memberRe.test(item))
          throw new Error(`${file}: bad variant member '${item}' in ${name}`);
      out.variants[name] = items;
    } else {
      const props = {};
      for (const item of items) {
        const m = propRe.exec(item);
        if (!m)
          throw new Error(`${file}: bad struct prop '${item}' in ${name}`);
        const [, prop, ty, isArray, isFlat] = m;
        // compact prop source form: 'T' | ['T'] (array) | ['T', null] (flat)
        props[prop] = isArray ? (isFlat ? [ty, null] : [ty]) : ty;
      }
      out.structs[name] = props;
    }
  }
  if (src.slice(lastEnd).trim() !== '')
    throw new Error(`${file}: trailing unparsed schema text`);
  return out;
}

// --- schemas.ts ---
const SCHEMA_NAMES = [
  'BRSavedGlobalDataSoA',
  'BRSavedOwnerTableSoA',
  'BRSavedBrickChunkIndexSoA',
  'BRSavedBrickChunkSoA',
  'BRSavedWireChunkSoA',
  'BRSavedComponentChunkSoA',
  'BRSavedComponentChunkSoA_max',
  'BRSavedEntityChunkIndexSoA',
  'BRSavedEntityChunkSoA',
];
const parsed = {};
for (const name of SCHEMA_NAMES) {
  const file = `${name}.schema`;
  parsed[name] = parseSchema(
    readFileSync(join(crate, 'schemas', file), 'utf8'),
    file
  );
}
let out = '// GENERATED by scripts/syncBrdbData.mjs — do not edit by hand.\n';
out += '// Regenerate with: just sync-brdb-data\n\n';
out += "import type { SchemaSource } from './schema';\n\n";
out += 'export type EmbeddedSchemaName =\n';
out += SCHEMA_NAMES.map(n => `  | '${n}'`).join('\n') + ';\n\n';
out += `export const SCHEMAS: Record<EmbeddedSchemaName, SchemaSource> = ${JSON.stringify(
  parsed,
  null,
  2
)};\n`;
writeFileSync('src/brdb/schemas.ts', out);

// --- catalog.ts ---
// assets/bricks.rs declares basic assets via BrickType::str("...") and
// procedural assets via BString::str("...").
const bricksRs = readFileSync(join(crate, 'src/assets/bricks.rs'), 'utf8');
const basic = [...bricksRs.matchAll(/BrickType::str\("([^"]+)"\)/g)].map(
  m => m[1]
);
const procedural = [...bricksRs.matchAll(/BString::str\("([^"]+)"\)/g)].map(
  m => m[1]
);
if (basic.length < 100 || procedural.length < 30)
  throw new Error(
    `catalog extraction failed (basic=${basic.length}, procedural=${procedural.length}) — check the regexes against assets/bricks.rs`
  );
let cat = '// GENERATED by scripts/syncBrdbData.mjs — do not edit by hand.\n';
cat += '// Regenerate with: just sync-brdb-data\n\n';
cat += `export const BASIC_BRICK_ASSETS: readonly string[] = ${JSON.stringify(
  basic,
  null,
  2
)};\n\n`;
cat += `export const PROCEDURAL_BRICK_ASSETS: readonly string[] = ${JSON.stringify(
  procedural,
  null,
  2
)};\n\n`;
cat += `const BASIC = new Set(BASIC_BRICK_ASSETS);
const PROCEDURAL = new Set(PROCEDURAL_BRICK_ASSETS);

/** Classify a brick asset as procedural (parametric, carries a size) or basic. */
export function isProceduralAsset(name: string): boolean {
  if (PROCEDURAL.has(name)) return true;
  if (BASIC.has(name)) return false;
  // Fallback for assets not in the catalog: PB_*/BP_* families are procedural.
  return name.startsWith('PB_') || name.startsWith('BP_');
}
`;
writeFileSync('src/brdb/catalog.ts', cat);

// --- componentDb.ts ---
// component_db.rs is autogenerated in the crate from a game dump; extract
// the component type->data-struct pairs, the wire port registry, and the
// entity type->class pairs.
const dbRs = readFileSync(join(crate, 'src/wrapper/component_db.rs'), 'utf8');

const extractPairs = tableName => {
  const m = dbRs.match(
    new RegExp(
      String.raw`pub static ${tableName}: &\[\(&str, &str\)\] = &\[([\s\S]*?)\n\];`
    )
  );
  if (!m) throw new Error(`component_db.rs: table ${tableName} not found`);
  return [...m[1].matchAll(/\("([^"]+)", "([^"]+)"\)/g)].map(p => [p[1], p[2]]);
};
const extractStrings = tableName => {
  const m = dbRs.match(
    new RegExp(
      String.raw`pub static ${tableName}: &\[&str\] = &\[([\s\S]*?)\n\];`
    )
  );
  if (!m) throw new Error(`component_db.rs: table ${tableName} not found`);
  return [...m[1].matchAll(/"([^"]+)"/g)].map(p => p[1]);
};

const componentPairs = extractPairs('COMPONENT_TYPE_STRUCT_PAIRS');
const wirePorts = extractStrings('WIRE_PORT_NAMES');
const entityPairs = extractPairs('ENTITY_TYPE_STRUCT_PAIRS');
if (componentPairs.length < 50 || wirePorts.length < 100 || !entityPairs.length)
  throw new Error(
    `component_db extraction failed (components=${componentPairs.length}, ports=${wirePorts.length}, entities=${entityPairs.length})`
  );

let db = '// GENERATED by scripts/syncBrdbData.mjs — do not edit by hand.\n';
db += '// Regenerate with: just sync-brdb-data\n\n';
db += `/** Component type name -> data struct name ("None" = no data struct). */
export const COMPONENT_TYPE_STRUCTS: ReadonlyMap<string, string> = new Map(
  ${JSON.stringify(componentPairs, null, 2)}
);

/** Known wire port names (a save's port registry is built from the ports
 * its wires actually use, but names must come from this vocabulary). */
export const WIRE_PORT_NAMES: readonly string[] = ${JSON.stringify(
  wirePorts,
  null,
  2
)};

/** Entity type name -> data class name. */
export const ENTITY_TYPE_STRUCTS: ReadonlyMap<string, string> = new Map(
  ${JSON.stringify(entityPairs, null, 2)}
);
`;
writeFileSync('src/brdb/componentDb.ts', db);

console.log(
  `generated schemas.ts (${SCHEMA_NAMES.length} schemas as data), catalog.ts (${basic.length} basic, ${procedural.length} procedural), componentDb.ts (${componentPairs.length} components, ${wirePorts.length} ports, ${entityPairs.length} entities)`
);
