// Regenerates src/brdb/schemas.ts and src/brdb/catalog.ts from a crate checkout.
// Usage: node scripts/syncBrdbData.mjs [path-to-brdb-crate-checkout]
//
// Schemas are parsed HERE, at generation time, and emitted as plain object
// literals — the runtime hydrates data instead of parsing schema text. This
// parser is the generation-time twin of src/brdb/schemaText.ts; any drift
// between them is caught by the schema byte-gate tests (embedded schema ->
// binary must equal the crate-serialized fixtures).
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const crate = join(process.argv[2] ?? '../brdb', 'crates/brdb');
// data/componentInventory.json is a checked-in game dump: the FULL brick
// asset registry plus per-component host bricks and wire port names (the
// crate's assets/bricks.rs only covers its curated constants). Regenerate
// it from a zoo world with scripts/extractInventory.mjs.
const inventoryPath = new URL(
  '../data/componentInventory.json',
  import.meta.url
);

// --- plaintext schema parser (generation-time only) ---

const IDENT = String.raw`[A-Za-z_]\w*(?:::\w+)*`;
const enumEntryRe = new RegExp(
  String.raw`^(${IDENT})\s*=\s*(-?\d+(?:_\d+)*|0b[01]+(?:_[01]+)*|0x[0-9a-fA-F]+(?:_[0-9a-fA-F]+)*)$`
);
const memberRe = new RegExp(String.raw`^${IDENT}$`);
const propRe = new RegExp(
  String.raw`^(\w+)\s*:\s*(\w+)\s*(\[\s*(flat)?\s*\])?$`
);

const stripComments = text =>
  text
    .replace(/\/\*[\s\S]*?\*\//g, ' ')
    .replace(/\/\/[^\n]*/g, ' ')
    .replace(/#[^\n]*/g, ' ');

const parseIntLiteral = raw => {
  const t = raw.replace(/_/g, '');
  if (t.startsWith('0b')) return parseInt(t.slice(2), 2);
  if (t.startsWith('0x')) return parseInt(t.slice(2), 16);
  return parseInt(t, 10);
};

function parseSchema(text, file) {
  const src = stripComments(text);
  const out = { enums: {}, variants: {}, structs: {} };
  const declRe = /\b(enum|variant|struct)\s+([A-Za-z0-9_]+)\s*\{([^{}]*)\}/g;
  let lastEnd = 0;
  let match;
  while ((match = declRe.exec(src))) {
    if (src.slice(lastEnd, match.index).trim() !== '')
      throw new Error(`${file}: unexpected text before ${match[2]}`);
    lastEnd = declRe.lastIndex;
    const [, keyword, name, body] = match;
    const items = body
      .split(',')
      .map(s => s.trim())
      .filter(s => s !== '');
    if (keyword === 'enum') {
      const values = {};
      for (const item of items) {
        const m = enumEntryRe.exec(item);
        if (!m) throw new Error(`${file}: bad enum entry '${item}' in ${name}`);
        values[m[1]] = parseIntLiteral(m[2]);
      }
      out.enums[name] = values;
    } else if (keyword === 'variant') {
      for (const item of items)
        if (!memberRe.test(item))
          throw new Error(`${file}: bad variant member '${item}' in ${name}`);
      out.variants[name] = items;
    } else {
      const props = {};
      for (const item of items) {
        const m = propRe.exec(item);
        if (!m)
          throw new Error(`${file}: bad struct prop '${item}' in ${name}`);
        const [, prop, ty, isArray, isFlat] = m;
        // compact prop source form: 'T' | ['T'] (array) | ['T', null] (flat)
        props[prop] = isArray ? (isFlat ? [ty, null] : [ty]) : ty;
      }
      out.structs[name] = props;
    }
  }
  if (src.slice(lastEnd).trim() !== '')
    throw new Error(`${file}: trailing unparsed schema text`);
  return out;
}

// --- schemas.ts ---
const SCHEMA_NAMES = [
  'BRSavedGlobalDataSoA',
  'BRSavedOwnerTableSoA',
  'BRSavedBrickChunkIndexSoA',
  'BRSavedBrickChunkSoA',
  'BRSavedWireChunkSoA',
  'BRSavedComponentChunkSoA',
  'BRSavedComponentChunkSoA_max',
  'BRSavedEntityChunkIndexSoA',
  'BRSavedEntityChunkSoA',
];
const parsed = {};
for (const name of SCHEMA_NAMES) {
  const file = `${name}.schema`;
  parsed[name] = parseSchema(
    readFileSync(join(crate, 'schemas', file), 'utf8'),
    file
  );
}
let out = '// GENERATED by scripts/syncBrdbData.mjs — do not edit by hand.\n';
out += '// Regenerate with: just sync-brdb-data\n\n';
out += "import type { SchemaSource } from './schema';\n\n";
out += 'export type EmbeddedSchemaName =\n';
out += SCHEMA_NAMES.map(n => `  | '${n}'`).join('\n') + ';\n\n';
out += `export const SCHEMAS: Record<EmbeddedSchemaName, SchemaSource> = ${JSON.stringify(
  parsed,
  null,
  2
)};\n`;
writeFileSync('src/brdb/schemas.ts', out);

// --- catalog.ts ---
// assets/bricks.rs declares basic assets via BrickType::str("...") and
// procedural assets via BString::str("...").
const bricksRs = readFileSync(join(crate, 'src/assets/bricks.rs'), 'utf8');
const crateBasic = [...bricksRs.matchAll(/BrickType::str\("([^"]+)"\)/g)].map(
  m => m[1]
);
const crateProcedural = [
  ...bricksRs.matchAll(/BString::str\("([^"]+)"\)/g),
].map(m => m[1]);
const inventory = JSON.parse(readFileSync(inventoryPath, 'utf8'));
// Union: crate list first (stable order), then dump-only assets sorted.
const union = (crateList, dumpList) => {
  const seen = new Set(crateList);
  return [...crateList, ...dumpList.filter(n => !seen.has(n)).sort()];
};
const basic = union(crateBasic, inventory.allBrickAssets);
const procedural = union(
  crateProcedural,
  inventory.proceduralBrickAssets ?? []
);
if (basic.length < 240 || procedural.length < 30)
  throw new Error(
    `catalog extraction failed (basic=${basic.length}, procedural=${procedural.length}) — check assets/bricks.rs and data/componentInventory.json`
  );
let cat = '// GENERATED by scripts/syncBrdbData.mjs — do not edit by hand.\n';
cat += '// Regenerate with: just sync-brdb-data\n\n';
cat += `export const BASIC_BRICK_ASSETS: readonly string[] = ${JSON.stringify(
  basic,
  null,
  2
)};\n\n`;
cat += `export const PROCEDURAL_BRICK_ASSETS: readonly string[] = ${JSON.stringify(
  procedural,
  null,
  2
)};\n\n`;
cat += `/** Every known brick asset name (basic + procedural), self-keyed for
 * typo-safe references with editor completion, e.g.
 * \`BRICK_ASSETS.B_1x1_Gate_MicrochipInput\`. */
export const BRICK_ASSETS = {
${[...basic, ...procedural]
  .sort()
  .map(n => `  ${n}: '${n}',`)
  .join('\n')}
} as const;

`;
cat += `const BASIC = new Set(BASIC_BRICK_ASSETS);
const PROCEDURAL = new Set(PROCEDURAL_BRICK_ASSETS);

/** Classify a brick asset as procedural (parametric, carries a size) or basic. */
export function isProceduralAsset(name: string): boolean {
  if (PROCEDURAL.has(name)) return true;
  if (BASIC.has(name)) return false;
  // Fallback for assets not in the catalog: PB_*/BP_* families are procedural.
  return name.startsWith('PB_') || name.startsWith('BP_');
}
`;
writeFileSync('src/brdb/catalog.ts', cat);

// --- componentDb.ts ---
// component_db.rs is autogenerated in the crate from a game dump; extract
// the component type->data-struct pairs, the wire port registry, and the
// entity type->class pairs.
const dbRs = readFileSync(join(crate, 'src/wrapper/component_db.rs'), 'utf8');

const extractPairs = tableName => {
  const m = dbRs.match(
    new RegExp(
      String.raw`pub static ${tableName}: &\[\(&str, &str\)\] = &\[([\s\S]*?)\n\];`
    )
  );
  if (!m) throw new Error(`component_db.rs: table ${tableName} not found`);
  return [...m[1].matchAll(/\("([^"]+)", "([^"]+)"\)/g)].map(p => [p[1], p[2]]);
};
const extractStrings = tableName => {
  const m = dbRs.match(
    new RegExp(
      String.raw`pub static ${tableName}: &\[&str\] = &\[([\s\S]*?)\n\];`
    )
  );
  if (!m) throw new Error(`component_db.rs: table ${tableName} not found`);
  return [...m[1].matchAll(/"([^"]+)"/g)].map(p => p[1]);
};

const componentPairs = extractPairs('COMPONENT_TYPE_STRUCT_PAIRS');
const wirePorts = extractStrings('WIRE_PORT_NAMES');
const entityPairs = extractPairs('ENTITY_TYPE_STRUCT_PAIRS');
if (componentPairs.length < 50 || wirePorts.length < 100 || !entityPairs.length)
  throw new Error(
    `component_db extraction failed (components=${componentPairs.length}, ports=${wirePorts.length}, entities=${entityPairs.length})`
  );

// STRUCT_DEFAULTS: component data struct -> game-default field values.
// Values are Rust expressions; translate the four forms that occur.
const translateDefault = (expr, ctx) => {
  if (expr === 'true') return true;
  if (expr === 'false') return false;
  const num =
    /^(-?\d+(?:\.\d+)?(?:[eE]-?\d+)?)(?:f32|f64|[iu](?:8|16|32|64))?$/.exec(
      expr
    );
  if (num) return Number(num[1]);
  const str = /^String::from\("([^"]*)"\)$/.exec(expr);
  if (str) return str[1];
  const color =
    /^SavedBrickColor \{ r: (\d+), g: (\d+), b: (\d+), a: (\d+) \}$/.exec(expr);
  // Field order matches the embedded Color struct (B, G, R, A).
  if (color) return { B: +color[3], G: +color[2], R: +color[1], A: +color[4] };
  throw new Error(`STRUCT_DEFAULTS: unhandled default at ${ctx}: ${expr}`);
};
const defaultsStart = dbRs.indexOf('pub static STRUCT_DEFAULTS');
if (defaultsStart < 0)
  throw new Error('component_db.rs: STRUCT_DEFAULTS not found');
const defaultsSrc = dbRs.slice(defaultsStart);
const structDefaults = {};
for (const [, structName, body] of defaultsSrc.matchAll(
  /\("([^"]+)", vec!\[([^\]]*)\]/g
)) {
  const fields = {};
  const pairs = [
    ...body.matchAll(/\("([^"]+)",\s*Box::new\((.+?)\)(?: as Box<[^>]+>)?\),/g),
  ];
  const declared = [...body.matchAll(/\("([^"]+)",\s*Box::new\(/g)].length;
  if (pairs.length !== declared)
    throw new Error(`STRUCT_DEFAULTS: unparsed field in ${structName}`);
  for (const [, field, expr] of pairs)
    fields[field] = translateDefault(expr, `${structName}.${field}`);
  structDefaults[structName] = fields;
}
if (Object.keys(structDefaults).length < 100)
  throw new Error(
    `STRUCT_DEFAULTS extraction failed (${
      Object.keys(structDefaults).length
    } structs)`
  );

// Per-component host bricks and wire port names, from the game dump.
const componentPorts = {};
for (const c of inventory.components)
  componentPorts[c.class] = {
    bricks: c.bricks,
    inputs: c.inputs,
    outputs: c.outputs,
  };
if (Object.keys(componentPorts).length < 200)
  throw new Error(
    `inventory component extraction failed (${
      Object.keys(componentPorts).length
    })`
  );

// COMPONENTS: ergonomic authoring constants, e.g.
// COMPONENTS.PlayAudioAt.NAME / .BRICK / .PORTS.Exec
// Keys keep the catalog's own casing (PlayAudioAt), minus the type-system
// prefixes; port keys are the port names verbatim.
const componentKey = cls =>
  cls
    .replace(/^BrickComponentType_/, '')
    .replace(/^BrickComponent_/, '')
    .replace(/^Component_/, '')
    .replace(/^WireGraphPseudo_/, '')
    .replace(/^WireGraph_/, '')
    .replace(/^Internal_/, '');
const componentsConst = {};
for (const c of inventory.components) {
  const key = componentKey(c.class);
  if (componentsConst[key])
    throw new Error(
      `COMPONENTS key collision: ${key} (${c.class} vs ${componentsConst[key].NAME})`
    );
  const ports = {};
  // '.' is not identifier-safe: 'InputA.X' keys as InputA_X
  for (const p of [...c.inputs, ...c.outputs]) ports[p.replace(/\./g, '_')] = p;
  componentsConst[key] = {
    NAME: c.class,
    BRICK: c.bricks[0],
    BRICKS: c.bricks,
    PORTS: ports,
  };
}

let db = '// GENERATED by scripts/syncBrdbData.mjs — do not edit by hand.\n';
db += '// Regenerate with: just sync-brdb-data\n\n';
db += "import type { BrdbValue } from './schema';\n\n";
db += `/** Component type name -> data struct name ("None" = no data struct). */
export const COMPONENT_TYPE_STRUCTS: ReadonlyMap<string, string> = new Map(
  ${JSON.stringify(componentPairs, null, 2)}
);

/** Component data struct name -> the game's default field values (the
 * reference crate's STRUCT_DEFAULTS). The writer fills omitted component
 * fields from here; fields with no default zero-fill. */
export const COMPONENT_STRUCT_DEFAULTS: ReadonlyMap<
  string,
  Readonly<Record<string, BrdbValue>>
> = new Map(
  Object.entries(${JSON.stringify(structDefaults, null, 2)})
);

/** Known wire port names (a save's port registry is built from the ports
 * its wires actually use, but names must come from this vocabulary). */
export const WIRE_PORT_NAMES: readonly string[] = ${JSON.stringify(
  wirePorts,
  null,
  2
)};

/** Entity type name -> data class name. */
export const ENTITY_TYPE_STRUCTS: ReadonlyMap<string, string> = new Map(
  ${JSON.stringify(entityPairs, null, 2)}
);

export interface ComponentPortInfo {
  /** brick assets this component lives on */
  readonly bricks: readonly string[];
  /** wire input port names */
  readonly inputs: readonly string[];
  /** wire output port names */
  readonly outputs: readonly string[];
}

/** Component type name -> host brick assets and wire port names, from a
 * live game dump (data/componentInventory.json). */
export const COMPONENT_WIRE_PORTS: ReadonlyMap<string, ComponentPortInfo> =
  new Map(
    Object.entries(${JSON.stringify(componentPorts, null, 2)})
  );

/** Ergonomic authoring constants per component type:
 * \`COMPONENTS.PlayAudioAt.NAME\` (component type name), \`.BRICK\` (host
 * brick asset; \`.BRICKS\` lists all hosts), \`.PORTS.*\` (wire port names,
 * e.g. \`COMPONENTS.PlayAudioAt.PORTS.EXEC\`). */
export const COMPONENTS = ${JSON.stringify(componentsConst, null, 2)} as const;
`;
writeFileSync('src/brdb/componentDb.ts', db);

// --- componentTypes.ts ---
// TypeScript shapes for component data structs, generated from the "max"
// component schema, so `components: [{ type, data }]` completes in editors.
const maxSchema = parsed['BRSavedComponentChunkSoA_max'];
const tsTypeOf = ty => {
  switch (ty) {
    case 'u8':
    case 'u16':
    case 'u32':
    case 'u64':
    case 'i8':
    case 'i16':
    case 'i32':
    case 'i64':
    case 'f32':
    case 'f64':
      return 'number';
    case 'bool':
      return 'boolean';
    case 'str':
    case 'bundle_path_ref': // a string path on the wire
      return 'string';
    // asset references: index into external asset references, null = none
    case 'class':
    case 'object':
    case 'weak_object':
      return 'number | null';
    case 'wire_graph_variant':
    case 'wire_graph_prim_math_variant':
      return 'BrdbVariant';
  }
  if (maxSchema.enums[ty]) return 'number';
  if (maxSchema.variants[ty]) return 'BrdbVariant';
  if (maxSchema.structs[ty]) return ty;
  throw new Error(`componentTypes: unknown schema type ${ty}`);
};
const tsPropOf = src => {
  if (Array.isArray(src)) {
    const el = tsTypeOf(src[0]);
    return el.includes('|') ? `(${el})[]` : `${el}[]`;
  }
  return tsTypeOf(src);
};

let ct = '// GENERATED by scripts/syncBrdbData.mjs — do not edit by hand.\n';
ct += '// Regenerate with: just sync-brdb-data\n\n';
ct += "import type { BrdbValue, BrdbVariant } from './schema';\n\n";
// Type aliases (not interfaces) on purpose: aliases carry an implicit index
// signature, so struct values stay assignable to Record<string, BrdbValue>.
for (const [name, props] of Object.entries(maxSchema.structs)) {
  const fields = Object.entries(props)
    .map(([field, src]) => `  ${field}: ${tsPropOf(src)};`)
    .join('\n');
  ct += `export type ${name} = {\n${fields}\n};\n\n`;
}
// Component type name -> its data struct shape (None -> no data fields).
ct += `/** Component type name -> data struct shape, for editor completion. */
export type ComponentTypeDataMap = {\n${componentPairs
  .map(([type, struct]) => {
    const shape =
      struct !== 'None' && maxSchema.structs[struct]
        ? struct
        : struct === 'None'
        ? 'Record<string, never>'
        : 'Record<string, BrdbValue>';
    return `  ${type}: ${shape};`;
  })
  .join('\n')}\n};\n\n`;
ct += `/** Every known component type name. */
export type BrdbComponentTypeName = keyof ComponentTypeDataMap;\n`;
writeFileSync('src/brdb/componentTypes.ts', ct);

console.log(
  `generated schemas.ts (${SCHEMA_NAMES.length} schemas as data), catalog.ts (${basic.length} basic, ${procedural.length} procedural), componentDb.ts (${componentPairs.length} components, ${wirePorts.length} ports, ${entityPairs.length} entities)`
);
